/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (shar-opts.c)
 *  
 *  It has been AutoGen-ed  January  6, 2013 at 06:21:27 PM by AutoGen 5.17.2pre2
 *  From the definitions    shar-opts.def
 *  and the template file   options
 *
 * Generated from AutoOpts 37:1:12 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the shar author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * The shar program is copyrighted and licensed
 * under the following terms:
 *
 *  Copyright (C) 1994-2013 Free Software Foundation, Inc., all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *
 *  shar is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  shar is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __doxygen__
#define OPTION_CODE_COMPILE 1
#include "shar-opts.h"
#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
#define zCopyright      (shar_opt_strs+0)
#define zLicenseDescrip (shar_opt_strs+294)

/*
 *  global included definitions
 */
#include <string.h>

int initialization_done = 0;
int optidx = 0;

#ifndef NULL
#  define NULL 0
#endif

/*
 *  shar option static const strings
 */
static char const shar_opt_strs[10449] =
/*     0 */ "shar (GNU sharutils) 4.13.3\n"
            "Copyright (C) 1994-2013 Free Software Foundation, Inc., all rights reserved.\n"
            "This is free software. It is licensed for use, modification and\n"
            "redistribution under the terms of the\n"
            "GNU General Public License, version 3 or later\n"
            "    <http://gnu.org/licenses/gpl.html>\n\0"
/*   294 */ "shar is free software: you can redistribute it and/or modify it under the\n"
            "terms of the GNU General Public License as published by the Free Software\n"
            "Foundation, either version 3 of the License, or (at your option) any later\n"
            "version.\n\n"
            "shar is distributed in the hope that it will be useful, but WITHOUT ANY\n"
            "WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS\n"
            "FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more\n"
            "details.\n\n"
            "You should have received a copy of the GNU General Public License along\n"
            "with this program.  If not, see <http://www.gnu.org/licenses/>.\n\0"
/*   891 */ "specifying compression:\0"
/*   915 */ "specify compression for input files\0"
/*   951 */ "INTERMIX_TYPE\0"
/*   965 */ "intermix-type\0"
/*   979 */ "specify compaction (compression) program\0"
/*  1020 */ "COMPACTOR\0"
/*  1030 */ "compactor\0"
/*  1040 */ "pass LEVEL for compression\0"
/*  1067 */ "LEVEL_OF_COMPRESSION\0"
/*  1088 */ "level-of-compression\0"
/*  1109 */ "bzip2 and uuencode files\0"
/*  1134 */ "BZIP2\0"
/*  1140 */ "bzip2\0"
/*  1146 */ "gzip and uuencode files\0"
/*  1170 */ "GZIP\0"
/*  1175 */ "gzip\0"
/*  1180 */ "compress and uuencode files\0"
/*  1208 */ "COMPRESS\0"
/*  1217 */ "compress\0"
/*  1226 */ "This is an alias for 'level-of-compression'\0"
/*  1270 */ "level-for-gzip\0"
/*  1285 */ "pass bits (default 12) to compress\0"
/*  1320 */ "BITS_PER_CODE\0"
/*  1334 */ "bits-per-code\0"
/*  1348 */ "12\0"
/*  1351 */ "specifying file encoding methodology:\0"
/*  1389 */ "decide uuencoding for each file\0"
/*  1421 */ "MIXED_UUENCODE\0"
/*  1436 */ "mixed-uuencode\0"
/*  1451 */ "treat all files as binary\0"
/*  1477 */ "UUENCODE\0"
/*  1486 */ "uuencode\0"
/*  1495 */ "treat all files as text\0"
/*  1519 */ "TEXT_FILES\0"
/*  1530 */ "text-files\0"
/*  1541 */ "specifying file selection and output modes:\0"
/*  1585 */ "print output to file PREFIX.nn\0"
/*  1616 */ "OUTPUT_PREFIX\0"
/*  1630 */ "output-prefix\0"
/*  1644 */ "split archive, not files, to size\0"
/*  1678 */ "WHOLE_SIZE_LIMIT\0"
/*  1695 */ "whole-size-limit\0"
/*  1712 */ "split archive or files to size\0"
/*  1743 */ "SPLIT_SIZE_LIMIT\0"
/*  1760 */ "split-size-limit\0"
/*  1777 */ "read file list from a file\0"
/*  1804 */ "INPUT_FILE_LIST\0"
/*  1820 */ "input-file-list\0"
/*  1836 */ "read file list from standard input\0"
/*  1871 */ "STDIN_FILE_LIST\0"
/*  1887 */ "stdin-file-list\0"
/*  1903 */ "Controlling the shar headers:\0"
/*  1933 */ "use name to document the archive\0"
/*  1966 */ "ARCHIVE_NAME\0"
/*  1979 */ "archive-name\0"
/*  1992 */ "override the submitter name\0"
/*  2020 */ "SUBMITTER\0"
/*  2030 */ "submitter\0"
/*  2040 */ "output Submitted-by: & Archive-name: headers\0"
/*  2085 */ "NET_HEADERS\0"
/*  2097 */ "net-headers\0"
/*  2109 */ "start the shar with a cut line\0"
/*  2140 */ "CUT_MARK\0"
/*  2149 */ "cut-mark\0"
/*  2158 */ "translate messages in the script\0"
/*  2191 */ "TRANSLATE\0"
/*  2201 */ "translate\0"
/*  2211 */ "Protecting against transmission issues::\0"
/*  2252 */ "do not use `wc -c' to check size\0"
/*  2285 */ "NO_CHARACTER_COUNT\0"
/*  2304 */ "no-character-count\0"
/*  2323 */ "do not use md5sum digest to verify\0"
/*  2358 */ "NO_MD5_DIGEST\0"
/*  2372 */ "no-md5-digest\0"
/*  2386 */ "apply the prefix character on every line\0"
/*  2427 */ "FORCE_PREFIX\0"
/*  2440 */ "force-prefix\0"
/*  2453 */ "use delim to delimit the files\0"
/*  2484 */ "HERE_DELIMITER\0"
/*  2499 */ "here-delimiter\0"
/*  2514 */ "SHAR_EOF\0"
/*  2523 */ "Producing different kinds of shars::\0"
/*  2560 */ "produce very simple shars\0"
/*  2586 */ "VANILLA_OPERATION\0"
/*  2604 */ "vanilla-operation\0"
/*  2622 */ "use temporary files between programs\0"
/*  2659 */ "NO_PIPING\0"
/*  2669 */ "no-piping\0"
/*  2679 */ "blindly overwrite existing files\0"
/*  2712 */ "NO_CHECK_EXISTING\0"
/*  2730 */ "no-check-existing\0"
/*  2748 */ "ask user before overwriting files\0"
/*  2782 */ "QUERY_USER\0"
/*  2793 */ "query-user\0"
/*  2804 */ "do not restore modification times\0"
/*  2838 */ "NO_TIMESTAMP\0"
/*  2851 */ "no-timestamp\0"
/*  2864 */ "avoid verbose messages at unshar time\0"
/*  2902 */ "QUIET_UNSHAR\0"
/*  2915 */ "quiet-unshar\0"
/*  2928 */ "restore in one directory, despite hierarchy\0"
/*  2972 */ "BASENAME\0"
/*  2981 */ "basename\0"
/*  2990 */ "Internationalization options::\0"
/*  3021 */ "do not internationalize\0"
/*  3045 */ "NO_I18N\0"
/*  3053 */ "no-i18n\0"
/*  3061 */ "print directory with shar messages\0"
/*  3096 */ "PRINT_TEXT_DOMAIN_DIR\0"
/*  3118 */ "print-text-domain-dir\0"
/*  3140 */ "user feedback/entertainment:\0"
/*  3169 */ "do not output verbose messages\0"
/*  3200 */ "QUIET\0"
/*  3206 */ "quiet\0"
/*  3212 */ "This is an alias for 'quiet'\0"
/*  3241 */ "silent\0"
/*  3248 */ "Display extended usage information and exit\0"
/*  3292 */ "help\0"
/*  3297 */ "Extended usage information passed thru pager\0"
/*  3342 */ "more-help\0"
/*  3352 */ "Output version information and exit\0"
/*  3388 */ "version\0"
/*  3396 */ "Save the option state to a config file\0"
/*  3435 */ "save-opts\0"
/*  3445 */ "Load options from a config file\0"
/*  3477 */ "LOAD_OPTS\0"
/*  3487 */ "no-load-opts\0"
/*  3500 */ "no\0"
/*  3503 */ "SHAR\0"
/*  3508 */ "shar (GNU sharutils) - create a shell archive - Ver. 4.13.3\n"
            "USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [file ...]\n\0"
/*  3637 */ "$HOME\0"
/*  3643 */ ".sharrc\0"
/*  3651 */ "bug-gnu-utils@gnu.org\0"
/*  3673 */ "\n"
            "If no 'file's are specified, the list of input files is read from a\n"
            "standard input.  Standard input must not be a terminal.\n\0"
/*  3799 */ "\n"
            "'shar' creates \"shell archives\" (or shar files) which are in text format\n"
            "and can be emailed.  These files may be unpacked later by executing them\n"
            "with '/bin/sh'.  The resulting archive is sent to standard out unless the\n"
            "'-o' option is given.  A wide range of features provide extensive\n"
            "flexibility in manufacturing shars and in specifying 'shar' \"smartness\".\n"
            "Archives may be fairly simple ('--vanilla-operation') or essentially a\n"
            "mailable 'tar' archive.\n\n"
            "Options may be specified in any order until a 'file' argument is\n"
            "recognized.  If the '--intermix-type' option has been specified, more\n"
            "compression and encoding options will be recognized between the 'file'\n"
            "arguments.\n\n"
            "Though this program supports 'uuencode'-d files, they are deprecated.  If\n"
            "you are emailing files, please consider mime-encoded files.  If you do\n"
            "'uuencode', base 64 is the preferred encoding method.\n\0"
/*  4673 */ "shar (GNU sharutils) 4.13.3\0"
/*  4701 */ "shar (GNU sharutils) - create a shell archive - Ver. 4.13.3\n"
            "USAGE:  shar [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [file ...]\n\n\n"
            "specifying compression:\n\n"
            "   -p, --intermix-type        specify compression for input files\n"
            "                                - prohibits these options:\n"
            "                                vanilla-operation\n"
            "   -C, --compactor=str        specify compaction (compression) program\n"
            "                                - prohibits these options:\n"
            "                                vanilla-operation\n"
            "                                - may appear multiple times\n"
            "   -g, --level-of-compression=num pass LEVEL for compression\n"
            "                                - It must be in the range:\n"
            "                                  1 to 9\n"
            "       --level-for-gzip=num   This is an alias for 'level-of-compression'\n\n"
            "specifying file encoding methodology:\n\n"
            "   -M, --mixed-uuencode       decide uuencoding for each file\n"
            "   -B, --uuencode             treat all files as binary\n"
            "                                - an alternate for mixed-uuencode\n"
            "   -T, --text-files           treat all files as text\n"
            "                                - an alternate for mixed-uuencode\n\n"
            "specifying file selection and output modes:\n\n"
            "   -o, --output-prefix=str    print output to file PREFIX.nn\n"
            "   -l, --whole-size-limit=num split archive, not files, to size\n"
            "                                - requires these options:\n"
            "                                output-prefix\n"
            "                                - is scalable with a suffix: k/K/m/M/g/G/t/T\n"
            "                                - It must lie in one of the ranges:\n"
            "                                  8 to 1023, or\n"
            "                                  8192 to 4194304\n"
            "   -L, --split-size-limit=num split archive or files to size\n"
            "                                - requires these options:\n"
            "                                output-prefix\n"
            "                                - is scalable with a suffix: k/K/m/M/g/G/t/T\n"
            "                                - It must lie in one of the ranges:\n"
            "                                  8 to 1023, or\n"
            "                                  8192 to 4194304\n"
            "                                - an alternate for whole-size-limit\n"
            "   -I, --input-file-list=str  read file list from a file\n\n"
            "Controlling the shar headers:\n\n"
            "   -n, --archive-name=str     use name to document the archive\n"
            "   -s, --submitter=str        override the submitter name\n"
            "   -a, --net-headers          output Submitted-by: & Archive-name: headers\n"
            "                                - requires these options:\n"
            "                                archive-name\n"
            "   -c, --cut-mark             start the shar with a cut line\n"
            "   -t, --translate            translate messages in the script\n\n"
            "Protecting against transmission issues::\n\n"
            "       --no-character-count   do not use `wc -c' to check size\n"
            "   -D, --no-md5-digest        do not use md5sum digest to verify\n"
            "   -F, --force-prefix         apply the prefix character on every line\n"
            "   -d, --here-delimiter=str   use delim to delimit the files\n\n"
            "Producing different kinds of shars::\n\n"
            "   -V, --vanilla-operation    produce very simple shars\n"
            "   -P, --no-piping            use temporary files between programs\n"
            "   -x, --no-check-existing    blindly overwrite existing files\n"
            "   -X, --query-user           ask user before overwriting files\n"
            "                                - prohibits these options:\n"
            "                                vanilla-operation\n"
            "   -m, --no-timestamp         do not restore modification times\n"
            "   -Q, --quiet-unshar         avoid verbose messages at unshar time\n"
            "   -f, --basename             restore in one directory, despite hierarchy\n\n"
            "Internationalization options::\n\n"
            "       --no-i18n              do not internationalize\n"
            "       --print-text-domain-dir  print directory with shar messages\n\n"
            "user feedback/entertainment:\n\n"
            "   -q, --quiet                do not output verbose messages\n"
            "       --silent               This is an alias for 'quiet'\n\n"
            "version, usage and configuration options:\n\n"
            "   -v, --version[=arg]        Output version information and exit\n"
            "   -h, --help                 Display extended usage information and exit\n"
            "   -!, --more-help            Extended usage information passed thru pager\n"
            "   -R, --save-opts[=arg]      Save the option state to a config file\n"
            "   -r, --load-opts=str        Load options from a config file\n"
            "                                - disabled as --no-load-opts\n"
            "                                - may appear multiple times\n\n"
            "Options are specified by doubled hyphens and their name or by a single\n"
            "hyphen and the flag character.\n\n"
            "If no 'file's are specified, the list of input files is read from a\n"
            "standard input.  Standard input must not be a terminal.\n\n"
            "The following option preset mechanisms are supported:\n"
            " - reading file $HOME/.sharrc\n\n"
            "'shar' creates \"shell archives\" (or shar files) which are in text format\n"
            "and can be emailed.  These files may be unpacked later by executing them\n"
            "with '/bin/sh'.  The resulting archive is sent to standard out unless the\n"
            "'-o' option is given.  A wide range of features provide extensive\n"
            "flexibility in manufacturing shars and in specifying 'shar' \"smartness\".\n"
            "Archives may be fairly simple ('--vanilla-operation') or essentially a\n"
            "mailable 'tar' archive.\n\n"
            "Options may be specified in any order until a 'file' argument is\n"
            "recognized.  If the '--intermix-type' option has been specified, more\n"
            "compression and encoding options will be recognized between the 'file'\n"
            "arguments.\n\n"
            "Though this program supports 'uuencode'-d files, they are deprecated.  If\n"
            "you are emailing files, please consider mime-encoded files.  If you do\n"
            "'uuencode', base 64 is the preferred encoding method.\n\n"
            "please send bug reports to:  bug-gnu-utils@gnu.org\0"
/* 10319 */ "shar (GNU sharutils) - create a shell archive - Ver. 4.13.3\n"
            "USAGE:  shar [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [file ...]";

/*
 *  compression option description:
 */
#define COMPRESSION_DESC      (shar_opt_strs+891)
#define COMPRESSION_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  intermix-type option description with
 *  "Must also have options" and "Incompatible options":
 */
#define INTERMIX_TYPE_DESC      (shar_opt_strs+915)
#define INTERMIX_TYPE_NAME      (shar_opt_strs+951)
#define INTERMIX_TYPE_name      (shar_opt_strs+965)
static int const aIntermix_TypeCantList[] = {
    INDEX_OPT_VANILLA_OPERATION, NO_EQUIVALENT };
#define INTERMIX_TYPE_FLAGS     (OPTST_DISABLED)

/*
 *  compactor option description with
 *  "Must also have options" and "Incompatible options":
 */
#define COMPACTOR_DESC      (shar_opt_strs+979)
#define COMPACTOR_NAME      (shar_opt_strs+1020)
#define COMPACTOR_name      (shar_opt_strs+1030)
static int const aCompactorCantList[] = {
    INDEX_OPT_VANILLA_OPERATION, NO_EQUIVALENT };
#define COMPACTOR_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  level-of-compression option description:
 */
#define LEVEL_OF_COMPRESSION_DESC      (shar_opt_strs+1040)
#define LEVEL_OF_COMPRESSION_NAME      (shar_opt_strs+1067)
#define LEVEL_OF_COMPRESSION_name      (shar_opt_strs+1088)
#define LEVEL_OF_COMPRESSION_DFT_ARG   ((char const*)9)
#define LEVEL_OF_COMPRESSION_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  bzip2 option description:
 */
#define BZIP2_DESC      (shar_opt_strs+1109)
#define BZIP2_NAME      (shar_opt_strs+1134)
#define BZIP2_name      (shar_opt_strs+1140)
#define BZIP2_FLAGS     (OPTST_DISABLED | OPTST_DEPRECATED)

/*
 *  gzip option description:
 */
#define GZIP_DESC      (shar_opt_strs+1146)
#define GZIP_NAME      (shar_opt_strs+1170)
#define GZIP_name      (shar_opt_strs+1175)
#define GZIP_FLAGS     (OPTST_DISABLED | OPTST_DEPRECATED)

/*
 *  compress option description:
 */
#ifdef HAVE_COMPRESS
#define COMPRESS_DESC      (shar_opt_strs+1180)
#define COMPRESS_NAME      (shar_opt_strs+1208)
#define COMPRESS_name      (shar_opt_strs+1217)
#define COMPRESS_FLAGS     (OPTST_DISABLED | OPTST_DEPRECATED)

#else   /* disable compress */
#define COMPRESS_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define COMPRESS_NAME      NULL
#define COMPRESS_DESC      NULL
#define COMPRESS_name      NULL
#endif  /* HAVE_COMPRESS */

/*
 *  level-for-gzip option description:
 */
#define LEVEL_FOR_GZIP_DESC    (shar_opt_strs+1226)
#define LEVEL_FOR_GZIP_NAME    NULL
#define LEVEL_FOR_GZIP_name    (shar_opt_strs+1270)
#define LEVEL_FOR_GZIP_FLAGS     (LEVEL_OF_COMPRESSION_FLAGS | OPTST_ALIAS)

/*
 *  bits-per-code option description:
 */
#ifdef HAVE_COMPRESS
#define BITS_PER_CODE_DESC      (shar_opt_strs+1285)
#define BITS_PER_CODE_NAME      (shar_opt_strs+1320)
#define BITS_PER_CODE_name      (shar_opt_strs+1334)
#define BITS_PER_CODE_DFT_ARG   (shar_opt_strs+1348)
#define BITS_PER_CODE_FLAGS     (OPTST_DISABLED | OPTST_DEPRECATED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable bits-per-code */
#define BITS_PER_CODE_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define BITS_PER_CODE_DFT_ARG   NULL
#define BITS_PER_CODE_NAME      NULL
#define BITS_PER_CODE_DESC      NULL
#define BITS_PER_CODE_name      NULL
#endif  /* HAVE_COMPRESS */

/*
 *  encoding option description:
 */
#define ENCODING_DESC      (shar_opt_strs+1351)
#define ENCODING_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  mixed-uuencode option description:
 */
#define MIXED_UUENCODE_DESC      (shar_opt_strs+1389)
#define MIXED_UUENCODE_NAME      (shar_opt_strs+1421)
#define MIXED_UUENCODE_name      (shar_opt_strs+1436)
#define MIXED_UUENCODE_FLAGS     (OPTST_DISABLED)

/*
 *  uuencode option description:
 */
#define UUENCODE_DESC      (shar_opt_strs+1451)
#define UUENCODE_NAME      (shar_opt_strs+1477)
#define UUENCODE_name      (shar_opt_strs+1486)
#define UUENCODE_FLAGS     (OPTST_DISABLED)

/*
 *  text-files option description:
 */
#define TEXT_FILES_DESC      (shar_opt_strs+1495)
#define TEXT_FILES_NAME      (shar_opt_strs+1519)
#define TEXT_FILES_name      (shar_opt_strs+1530)
#define TEXT_FILES_FLAGS     (OPTST_DISABLED)

/*
 *  in-out option description:
 */
#define IN_OUT_DESC      (shar_opt_strs+1541)
#define IN_OUT_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  output-prefix option description:
 */
#define OUTPUT_PREFIX_DESC      (shar_opt_strs+1585)
#define OUTPUT_PREFIX_NAME      (shar_opt_strs+1616)
#define OUTPUT_PREFIX_name      (shar_opt_strs+1630)
#define OUTPUT_PREFIX_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  whole-size-limit option description with
 *  "Must also have options" and "Incompatible options":
 */
#define WHOLE_SIZE_LIMIT_DESC      (shar_opt_strs+1644)
#define WHOLE_SIZE_LIMIT_NAME      (shar_opt_strs+1678)
#define WHOLE_SIZE_LIMIT_name      (shar_opt_strs+1695)
static int const aWhole_Size_LimitMustList[] = {
    INDEX_OPT_OUTPUT_PREFIX, NO_EQUIVALENT };
#define WHOLE_SIZE_LIMIT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC) \
        | OPTST_SCALED_NUM)

/*
 *  split-size-limit option description with
 *  "Must also have options" and "Incompatible options":
 */
#define SPLIT_SIZE_LIMIT_DESC      (shar_opt_strs+1712)
#define SPLIT_SIZE_LIMIT_NAME      (shar_opt_strs+1743)
#define SPLIT_SIZE_LIMIT_name      (shar_opt_strs+1760)
static int const aSplit_Size_LimitMustList[] = {
    INDEX_OPT_OUTPUT_PREFIX, NO_EQUIVALENT };
#define SPLIT_SIZE_LIMIT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC) \
        | OPTST_SCALED_NUM)

/*
 *  input-file-list option description:
 */
#define INPUT_FILE_LIST_DESC      (shar_opt_strs+1777)
#define INPUT_FILE_LIST_NAME      (shar_opt_strs+1804)
#define INPUT_FILE_LIST_name      (shar_opt_strs+1820)
#define INPUT_FILE_LIST_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  stdin-file-list option description:
 */
#define STDIN_FILE_LIST_DESC      (shar_opt_strs+1836)
#define STDIN_FILE_LIST_NAME      (shar_opt_strs+1871)
#define STDIN_FILE_LIST_name      (shar_opt_strs+1887)
#define STDIN_FILE_LIST_FLAGS     (OPTST_DISABLED | OPTST_DEPRECATED)

/*
 *  headers option description:
 */
#define HEADERS_DESC      (shar_opt_strs+1903)
#define HEADERS_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  archive-name option description:
 */
#define ARCHIVE_NAME_DESC      (shar_opt_strs+1933)
#define ARCHIVE_NAME_NAME      (shar_opt_strs+1966)
#define ARCHIVE_NAME_name      (shar_opt_strs+1979)
#define ARCHIVE_NAME_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  submitter option description:
 */
#define SUBMITTER_DESC      (shar_opt_strs+1992)
#define SUBMITTER_NAME      (shar_opt_strs+2020)
#define SUBMITTER_name      (shar_opt_strs+2030)
#define SUBMITTER_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  net-headers option description with
 *  "Must also have options" and "Incompatible options":
 */
#define NET_HEADERS_DESC      (shar_opt_strs+2040)
#define NET_HEADERS_NAME      (shar_opt_strs+2085)
#define NET_HEADERS_name      (shar_opt_strs+2097)
static int const aNet_HeadersMustList[] = {
    INDEX_OPT_ARCHIVE_NAME, NO_EQUIVALENT };
#define NET_HEADERS_FLAGS     (OPTST_DISABLED)

/*
 *  cut-mark option description:
 */
#define CUT_MARK_DESC      (shar_opt_strs+2109)
#define CUT_MARK_NAME      (shar_opt_strs+2140)
#define CUT_MARK_name      (shar_opt_strs+2149)
#define CUT_MARK_FLAGS     (OPTST_DISABLED)

/*
 *  translate option description:
 */
#define TRANSLATE_DESC      (shar_opt_strs+2158)
#define TRANSLATE_NAME      (shar_opt_strs+2191)
#define TRANSLATE_name      (shar_opt_strs+2201)
#define TRANSLATE_FLAGS     (OPTST_DISABLED)

/*
 *  xmit-defenses option description:
 */
#define XMIT_DEFENSES_DESC      (shar_opt_strs+2211)
#define XMIT_DEFENSES_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  no-character-count option description:
 */
#define NO_CHARACTER_COUNT_DESC      (shar_opt_strs+2252)
#define NO_CHARACTER_COUNT_NAME      (shar_opt_strs+2285)
#define NO_CHARACTER_COUNT_name      (shar_opt_strs+2304)
#define NO_CHARACTER_COUNT_FLAGS     (OPTST_DISABLED)

/*
 *  no-md5-digest option description:
 */
#define NO_MD5_DIGEST_DESC      (shar_opt_strs+2323)
#define NO_MD5_DIGEST_NAME      (shar_opt_strs+2358)
#define NO_MD5_DIGEST_name      (shar_opt_strs+2372)
#define NO_MD5_DIGEST_FLAGS     (OPTST_DISABLED)

/*
 *  force-prefix option description:
 */
#define FORCE_PREFIX_DESC      (shar_opt_strs+2386)
#define FORCE_PREFIX_NAME      (shar_opt_strs+2427)
#define FORCE_PREFIX_name      (shar_opt_strs+2440)
#define FORCE_PREFIX_FLAGS     (OPTST_DISABLED)

/*
 *  here-delimiter option description:
 */
#define HERE_DELIMITER_DESC      (shar_opt_strs+2453)
#define HERE_DELIMITER_NAME      (shar_opt_strs+2484)
#define HERE_DELIMITER_name      (shar_opt_strs+2499)
#define HERE_DELIMITER_DFT_ARG   (shar_opt_strs+2514)
#define HERE_DELIMITER_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  shar-flavors option description:
 */
#define SHAR_FLAVORS_DESC      (shar_opt_strs+2523)
#define SHAR_FLAVORS_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  vanilla-operation option description:
 */
#define VANILLA_OPERATION_DESC      (shar_opt_strs+2560)
#define VANILLA_OPERATION_NAME      (shar_opt_strs+2586)
#define VANILLA_OPERATION_name      (shar_opt_strs+2604)
#define VANILLA_OPERATION_FLAGS     (OPTST_DISABLED)

/*
 *  no-piping option description:
 */
#define NO_PIPING_DESC      (shar_opt_strs+2622)
#define NO_PIPING_NAME      (shar_opt_strs+2659)
#define NO_PIPING_name      (shar_opt_strs+2669)
#define NO_PIPING_FLAGS     (OPTST_DISABLED)

/*
 *  no-check-existing option description:
 */
#define NO_CHECK_EXISTING_DESC      (shar_opt_strs+2679)
#define NO_CHECK_EXISTING_NAME      (shar_opt_strs+2712)
#define NO_CHECK_EXISTING_name      (shar_opt_strs+2730)
#define NO_CHECK_EXISTING_FLAGS     (OPTST_DISABLED)

/*
 *  query-user option description with
 *  "Must also have options" and "Incompatible options":
 */
#define QUERY_USER_DESC      (shar_opt_strs+2748)
#define QUERY_USER_NAME      (shar_opt_strs+2782)
#define QUERY_USER_name      (shar_opt_strs+2793)
static int const aQuery_UserCantList[] = {
    INDEX_OPT_VANILLA_OPERATION, NO_EQUIVALENT };
#define QUERY_USER_FLAGS     (OPTST_DISABLED)

/*
 *  no-timestamp option description:
 */
#define NO_TIMESTAMP_DESC      (shar_opt_strs+2804)
#define NO_TIMESTAMP_NAME      (shar_opt_strs+2838)
#define NO_TIMESTAMP_name      (shar_opt_strs+2851)
#define NO_TIMESTAMP_FLAGS     (OPTST_DISABLED)

/*
 *  quiet-unshar option description:
 */
#define QUIET_UNSHAR_DESC      (shar_opt_strs+2864)
#define QUIET_UNSHAR_NAME      (shar_opt_strs+2902)
#define QUIET_UNSHAR_name      (shar_opt_strs+2915)
#define QUIET_UNSHAR_FLAGS     (OPTST_DISABLED)

/*
 *  basename option description:
 */
#define BASENAME_DESC      (shar_opt_strs+2928)
#define BASENAME_NAME      (shar_opt_strs+2972)
#define BASENAME_name      (shar_opt_strs+2981)
#define BASENAME_FLAGS     (OPTST_DISABLED)

/*
 *  internationalization option description:
 */
#define INTERNATIONALIZATION_DESC      (shar_opt_strs+2990)
#define INTERNATIONALIZATION_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  no-i18n option description:
 */
#define NO_I18N_DESC      (shar_opt_strs+3021)
#define NO_I18N_NAME      (shar_opt_strs+3045)
#define NO_I18N_name      (shar_opt_strs+3053)
#define NO_I18N_FLAGS     (OPTST_DISABLED)

/*
 *  print-text-domain-dir option description:
 */
#define PRINT_TEXT_DOMAIN_DIR_DESC      (shar_opt_strs+3061)
#define PRINT_TEXT_DOMAIN_DIR_NAME      (shar_opt_strs+3096)
#define PRINT_TEXT_DOMAIN_DIR_name      (shar_opt_strs+3118)
#define PRINT_TEXT_DOMAIN_DIR_FLAGS     (OPTST_DISABLED)

/*
 *  feedback option description:
 */
#define FEEDBACK_DESC      (shar_opt_strs+3140)
#define FEEDBACK_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  quiet option description:
 */
#define QUIET_DESC      (shar_opt_strs+3169)
#define QUIET_NAME      (shar_opt_strs+3200)
#define QUIET_name      (shar_opt_strs+3206)
#define QUIET_FLAGS     (OPTST_DISABLED)

/*
 *  silent option description:
 */
#define SILENT_DESC    (shar_opt_strs+3212)
#define SILENT_NAME    NULL
#define SILENT_name    (shar_opt_strs+3241)
#define SILENT_FLAGS     (QUIET_FLAGS | OPTST_ALIAS)

/*
 *  Help/More_Help/Version option descriptions:
 */
#define HELP_DESC       (shar_opt_strs+3248)
#define HELP_name       (shar_opt_strs+3292)
#ifdef HAVE_WORKING_FORK
#define MORE_HELP_DESC  (shar_opt_strs+3297)
#define MORE_HELP_name  (shar_opt_strs+3342)
#define MORE_HELP_FLAGS (OPTST_IMM | OPTST_NO_INIT)
#else
#define MORE_HELP_DESC  NULL
#define MORE_HELP_name  NULL
#define MORE_HELP_FLAGS (OPTST_OMITTED | OPTST_NO_INIT)
#endif
#ifdef NO_OPTIONAL_OPT_ARGS
#  define VER_FLAGS     (OPTST_IMM | OPTST_NO_INIT)
#else
#  define VER_FLAGS     (OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | \
                         OPTST_ARG_OPTIONAL | OPTST_IMM | OPTST_NO_INIT)
#endif
#define VER_DESC        (shar_opt_strs+3352)
#define VER_name        (shar_opt_strs+3388)
#define SAVE_OPTS_DESC  (shar_opt_strs+3396)
#define SAVE_OPTS_name  (shar_opt_strs+3435)
#define LOAD_OPTS_DESC     (shar_opt_strs+3445)
#define LOAD_OPTS_NAME     (shar_opt_strs+3477)
#define NO_LOAD_OPTS_name  (shar_opt_strs+3487)
#define LOAD_OPTS_pfx      (shar_opt_strs+3500)
#define LOAD_OPTS_name     (NO_LOAD_OPTS_name + 3)
/*
 *  Declare option callback procedures
 */
#ifdef HAVE_COMPRESS
  static tOptProc doOptCompress;
#else /* not HAVE_COMPRESS */
# define doOptCompress NULL
#endif /* def/not HAVE_COMPRESS */
#ifdef HAVE_COMPRESS
  static tOptProc doOptBits_Per_Code;
#else /* not HAVE_COMPRESS */
# define doOptBits_Per_Code NULL
#endif /* def/not HAVE_COMPRESS */
extern tOptProc
    check_intermixing,    optionBooleanVal,     optionNestedVal,
    optionNumericVal,     optionPagedUsage,     optionPrintVersion,
    optionResetOpt,       optionStackArg,       optionTimeDate,
    optionTimeVal,        optionUnstackArg,     optionVendorOption,
    set_compaction,       validate_opt_context;
static tOptProc
    doOptBzip2,                 doOptGzip,
    doOptInput_File_List,       doOptLevel_For_Gzip,
    doOptLevel_Of_Compression,  doOptPrint_Text_Domain_Dir,
    doOptSilent,                doOptSplit_Size_Limit,
    doOptStdin_File_List,       doOptVanilla_Operation,
    doOptWhole_Size_Limit,      doUsageOpt;
#define VER_PROC        optionPrintVersion

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 *  Define the shar Option Descriptions.
 * This is an array of OPTION_CT entries, one for each
 * option that the shar program responds to.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ COMPRESSION_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ COMPRESSION_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_INTERMIX_TYPE,
     /* equiv idx, value */ 1, VALUE_OPT_INTERMIX_TYPE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INTERMIX_TYPE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --intermix-type */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aIntermix_TypeCantList,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ INTERMIX_TYPE_DESC, INTERMIX_TYPE_NAME, INTERMIX_TYPE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_COMPACTOR,
     /* equiv idx, value */ 2, VALUE_OPT_COMPACTOR,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ COMPACTOR_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --compactor */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aCompactorCantList,
     /* option proc      */ set_compaction,
     /* desc, NAME, name */ COMPACTOR_DESC, COMPACTOR_NAME, COMPACTOR_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 3, VALUE_OPT_LEVEL_OF_COMPRESSION,
     /* equiv idx, value */ 3, VALUE_OPT_LEVEL_OF_COMPRESSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LEVEL_OF_COMPRESSION_FLAGS, 0,
     /* last opt argumnt */ { LEVEL_OF_COMPRESSION_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLevel_Of_Compression,
     /* desc, NAME, name */ LEVEL_OF_COMPRESSION_DESC, LEVEL_OF_COMPRESSION_NAME, LEVEL_OF_COMPRESSION_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_BZIP2,
     /* equiv idx, value */ 4, VALUE_OPT_BZIP2,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ BZIP2_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --bzip2 */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptBzip2,
     /* desc, NAME, name */ BZIP2_DESC, BZIP2_NAME, BZIP2_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 5, VALUE_OPT_GZIP,
     /* equiv idx, value */ 5, VALUE_OPT_GZIP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ GZIP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --gzip */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptGzip,
     /* desc, NAME, name */ GZIP_DESC, GZIP_NAME, GZIP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_COMPRESS,
     /* equiv idx, value */ 6, VALUE_OPT_COMPRESS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ COMPRESS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --compress */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptCompress,
     /* desc, NAME, name */ COMPRESS_DESC, COMPRESS_NAME, COMPRESS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 7, VALUE_OPT_LEVEL_FOR_GZIP,
     /* equiv idx, value */ 7, VALUE_OPT_LEVEL_FOR_GZIP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LEVEL_FOR_GZIP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --level-for-gzip */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLevel_For_Gzip,
     /* desc, NAME, name */ LEVEL_FOR_GZIP_DESC, LEVEL_FOR_GZIP_NAME, LEVEL_FOR_GZIP_name,
     /* disablement strs */ 0, 0 },

  {  /* entry idx, value */ 8, VALUE_OPT_BITS_PER_CODE,
     /* equiv idx, value */ 8, VALUE_OPT_BITS_PER_CODE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ BITS_PER_CODE_FLAGS, 0,
     /* last opt argumnt */ { BITS_PER_CODE_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptBits_Per_Code,
     /* desc, NAME, name */ BITS_PER_CODE_DESC, BITS_PER_CODE_NAME, BITS_PER_CODE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ ENCODING_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENCODING_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 10, VALUE_OPT_MIXED_UUENCODE,
     /* equiv idx, value */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MIXED_UUENCODE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --mixed-uuencode */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ check_intermixing,
     /* desc, NAME, name */ MIXED_UUENCODE_DESC, MIXED_UUENCODE_NAME, MIXED_UUENCODE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 11, VALUE_OPT_UUENCODE,
     /* equiv idx, value */ NOLIMIT, NOLIMIT,
     /* equivalenced to  */ INDEX_OPT_MIXED_UUENCODE,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ UUENCODE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --uuencode */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ check_intermixing,
     /* desc, NAME, name */ UUENCODE_DESC, UUENCODE_NAME, UUENCODE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 12, VALUE_OPT_TEXT_FILES,
     /* equiv idx, value */ NOLIMIT, NOLIMIT,
     /* equivalenced to  */ INDEX_OPT_MIXED_UUENCODE,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TEXT_FILES_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --text-files */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ check_intermixing,
     /* desc, NAME, name */ TEXT_FILES_DESC, TEXT_FILES_NAME, TEXT_FILES_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ IN_OUT_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ IN_OUT_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 14, VALUE_OPT_OUTPUT_PREFIX,
     /* equiv idx, value */ 14, VALUE_OPT_OUTPUT_PREFIX,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OUTPUT_PREFIX_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --output-prefix */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ OUTPUT_PREFIX_DESC, OUTPUT_PREFIX_NAME, OUTPUT_PREFIX_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 15, VALUE_OPT_WHOLE_SIZE_LIMIT,
     /* equiv idx, value */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ WHOLE_SIZE_LIMIT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --whole-size-limit */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aWhole_Size_LimitMustList, NULL,
     /* option proc      */ doOptWhole_Size_Limit,
     /* desc, NAME, name */ WHOLE_SIZE_LIMIT_DESC, WHOLE_SIZE_LIMIT_NAME, WHOLE_SIZE_LIMIT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 16, VALUE_OPT_SPLIT_SIZE_LIMIT,
     /* equiv idx, value */ NOLIMIT, NOLIMIT,
     /* equivalenced to  */ INDEX_OPT_WHOLE_SIZE_LIMIT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SPLIT_SIZE_LIMIT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --split-size-limit */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aSplit_Size_LimitMustList, NULL,
     /* option proc      */ doOptSplit_Size_Limit,
     /* desc, NAME, name */ SPLIT_SIZE_LIMIT_DESC, SPLIT_SIZE_LIMIT_NAME, SPLIT_SIZE_LIMIT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 17, VALUE_OPT_INPUT_FILE_LIST,
     /* equiv idx, value */ 17, VALUE_OPT_INPUT_FILE_LIST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INPUT_FILE_LIST_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --input-file-list */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptInput_File_List,
     /* desc, NAME, name */ INPUT_FILE_LIST_DESC, INPUT_FILE_LIST_NAME, INPUT_FILE_LIST_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 18, VALUE_OPT_STDIN_FILE_LIST,
     /* equiv idx, value */ 18, VALUE_OPT_STDIN_FILE_LIST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ STDIN_FILE_LIST_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --stdin-file-list */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptStdin_File_List,
     /* desc, NAME, name */ STDIN_FILE_LIST_DESC, STDIN_FILE_LIST_NAME, STDIN_FILE_LIST_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ HEADERS_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ HEADERS_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 20, VALUE_OPT_ARCHIVE_NAME,
     /* equiv idx, value */ 20, VALUE_OPT_ARCHIVE_NAME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ARCHIVE_NAME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --archive-name */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ ARCHIVE_NAME_DESC, ARCHIVE_NAME_NAME, ARCHIVE_NAME_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 21, VALUE_OPT_SUBMITTER,
     /* equiv idx, value */ 21, VALUE_OPT_SUBMITTER,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SUBMITTER_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --submitter */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ SUBMITTER_DESC, SUBMITTER_NAME, SUBMITTER_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 22, VALUE_OPT_NET_HEADERS,
     /* equiv idx, value */ 22, VALUE_OPT_NET_HEADERS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NET_HEADERS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --net-headers */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aNet_HeadersMustList, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ NET_HEADERS_DESC, NET_HEADERS_NAME, NET_HEADERS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 23, VALUE_OPT_CUT_MARK,
     /* equiv idx, value */ 23, VALUE_OPT_CUT_MARK,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CUT_MARK_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --cut-mark */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ CUT_MARK_DESC, CUT_MARK_NAME, CUT_MARK_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 24, VALUE_OPT_TRANSLATE,
     /* equiv idx, value */ 24, VALUE_OPT_TRANSLATE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TRANSLATE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --translate */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ TRANSLATE_DESC, TRANSLATE_NAME, TRANSLATE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ XMIT_DEFENSES_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ XMIT_DEFENSES_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 26, VALUE_OPT_NO_CHARACTER_COUNT,
     /* equiv idx, value */ 26, VALUE_OPT_NO_CHARACTER_COUNT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NO_CHARACTER_COUNT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --no-character-count */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ NO_CHARACTER_COUNT_DESC, NO_CHARACTER_COUNT_NAME, NO_CHARACTER_COUNT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 27, VALUE_OPT_NO_MD5_DIGEST,
     /* equiv idx, value */ 27, VALUE_OPT_NO_MD5_DIGEST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NO_MD5_DIGEST_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --no-md5-digest */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ NO_MD5_DIGEST_DESC, NO_MD5_DIGEST_NAME, NO_MD5_DIGEST_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 28, VALUE_OPT_FORCE_PREFIX,
     /* equiv idx, value */ 28, VALUE_OPT_FORCE_PREFIX,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FORCE_PREFIX_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --force-prefix */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ FORCE_PREFIX_DESC, FORCE_PREFIX_NAME, FORCE_PREFIX_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 29, VALUE_OPT_HERE_DELIMITER,
     /* equiv idx, value */ 29, VALUE_OPT_HERE_DELIMITER,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ HERE_DELIMITER_FLAGS, 0,
     /* last opt argumnt */ { HERE_DELIMITER_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ HERE_DELIMITER_DESC, HERE_DELIMITER_NAME, HERE_DELIMITER_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ SHAR_FLAVORS_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SHAR_FLAVORS_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 31, VALUE_OPT_VANILLA_OPERATION,
     /* equiv idx, value */ 31, VALUE_OPT_VANILLA_OPERATION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VANILLA_OPERATION_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --vanilla-operation */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptVanilla_Operation,
     /* desc, NAME, name */ VANILLA_OPERATION_DESC, VANILLA_OPERATION_NAME, VANILLA_OPERATION_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 32, VALUE_OPT_NO_PIPING,
     /* equiv idx, value */ 32, VALUE_OPT_NO_PIPING,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NO_PIPING_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --no-piping */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ NO_PIPING_DESC, NO_PIPING_NAME, NO_PIPING_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 33, VALUE_OPT_NO_CHECK_EXISTING,
     /* equiv idx, value */ 33, VALUE_OPT_NO_CHECK_EXISTING,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NO_CHECK_EXISTING_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --no-check-existing */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ NO_CHECK_EXISTING_DESC, NO_CHECK_EXISTING_NAME, NO_CHECK_EXISTING_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 34, VALUE_OPT_QUERY_USER,
     /* equiv idx, value */ 34, VALUE_OPT_QUERY_USER,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ QUERY_USER_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --query-user */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aQuery_UserCantList,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ QUERY_USER_DESC, QUERY_USER_NAME, QUERY_USER_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 35, VALUE_OPT_NO_TIMESTAMP,
     /* equiv idx, value */ 35, VALUE_OPT_NO_TIMESTAMP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NO_TIMESTAMP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --no-timestamp */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ NO_TIMESTAMP_DESC, NO_TIMESTAMP_NAME, NO_TIMESTAMP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 36, VALUE_OPT_QUIET_UNSHAR,
     /* equiv idx, value */ 36, VALUE_OPT_QUIET_UNSHAR,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ QUIET_UNSHAR_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --quiet-unshar */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ QUIET_UNSHAR_DESC, QUIET_UNSHAR_NAME, QUIET_UNSHAR_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 37, VALUE_OPT_BASENAME,
     /* equiv idx, value */ 37, VALUE_OPT_BASENAME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ BASENAME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --basename */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ BASENAME_DESC, BASENAME_NAME, BASENAME_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ INTERNATIONALIZATION_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ INTERNATIONALIZATION_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 39, VALUE_OPT_NO_I18N,
     /* equiv idx, value */ 39, VALUE_OPT_NO_I18N,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NO_I18N_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --no-i18n */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ NO_I18N_DESC, NO_I18N_NAME, NO_I18N_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 40, VALUE_OPT_PRINT_TEXT_DOMAIN_DIR,
     /* equiv idx, value */ 40, VALUE_OPT_PRINT_TEXT_DOMAIN_DIR,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PRINT_TEXT_DOMAIN_DIR_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --print-text-domain-dir */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptPrint_Text_Domain_Dir,
     /* desc, NAME, name */ PRINT_TEXT_DOMAIN_DIR_DESC, PRINT_TEXT_DOMAIN_DIR_NAME, PRINT_TEXT_DOMAIN_DIR_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ FEEDBACK_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ FEEDBACK_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 42, VALUE_OPT_QUIET,
     /* equiv idx, value */ 42, VALUE_OPT_QUIET,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ QUIET_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --quiet */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ validate_opt_context,
     /* desc, NAME, name */ QUIET_DESC, QUIET_NAME, QUIET_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 43, VALUE_OPT_SILENT,
     /* equiv idx, value */ 43, VALUE_OPT_SILENT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SILENT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --silent */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptSilent,
     /* desc, NAME, name */ SILENT_DESC, SILENT_NAME, SILENT_name,
     /* disablement strs */ 0, 0 },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_VERSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VER_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ VER_PROC,
     /* desc, NAME, name */ VER_DESC, NULL, VER_name,
     /* disablement strs */ NULL, NULL },



  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ HELP_DESC, NULL, HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_MORE_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ MORE_HELP_DESC, NULL, MORE_HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_SAVE_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SAVE_OPTS_DESC, NULL, SAVE_OPTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_LOAD_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
			  | OPTST_DISABLE_IMM, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionLoadOpt,
     /* desc, NAME, name */ LOAD_OPTS_DESC, LOAD_OPTS_NAME, LOAD_OPTS_name,
     /* disablement strs */ NO_LOAD_OPTS_name, LOAD_OPTS_pfx }
};


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the shar Option Environment
 */
#define zPROGNAME       (shar_opt_strs+3503)
#define zUsageTitle     (shar_opt_strs+3508)
#define zRcName         (shar_opt_strs+3643)
static char const * const apzHomeList[2] = {
    shar_opt_strs+3637,
    NULL };
#define zBugsAddr       (shar_opt_strs+3651)
#define zExplain        (shar_opt_strs+3673)
#define zDetail         (shar_opt_strs+3799)
#define zFullVersion    (shar_opt_strs+4673)
/* extracted from optcode.tlib near line 353 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */


#define shar_full_usage (shar_opt_strs+4701)

#define shar_short_usage (shar_opt_strs+10319)

#endif /* not defined __doxygen__ */

/*
 *  Create the static procedure(s) declared above.
 */
/**
 * The callout function that invokes the optionUsage function.
 *
 * @param pOptions the AutoOpts option description structure
 * @param pOptDesc the descriptor for the "help" (usage) option.
 * @noreturn
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    optionUsage(&sharOptions, SHAR_EXIT_SUCCESS);
    /* NOTREACHED */
    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the level-of-compression option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptLevel_Of_Compression(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 1, 9 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

 emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the bzip2 option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptBzip2(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from shar-opts.def, line 142 */
    SET_OPT_COMPACTOR("bzip2");
    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the gzip option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptGzip(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from shar-opts.def, line 156 */
    SET_OPT_COMPACTOR("gzip");
    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the compress option, when HAVE_COMPRESS is #define-d.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
#ifdef HAVE_COMPRESS
static void
doOptCompress(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from shar-opts.def, line 171 */
    SET_OPT_COMPACTOR("compress");
    (void)pOptDesc;
    (void)pOptions;
}
#endif /* defined HAVE_COMPRESS */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the level-for-gzip option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptLevel_For_Gzip(tOptions* pOptions, tOptDesc* pOptDesc)
{
    int res = optionAlias(pOptions, pOptDesc, INDEX_OPT_LEVEL_OF_COMPRESSION);
    if ((res != 0) && ((pOptions->fOptSet & OPTPROC_ERRSTOP) != 0))
        USAGE(SHAR_EXIT_USAGE_ERROR);

}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the bits-per-code option, when HAVE_COMPRESS is #define-d.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
#ifdef HAVE_COMPRESS
static void
doOptBits_Per_Code(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from shar-opts.def, line 193 */
    check_intermixing(pOptions, pOptDesc);
    SET_OPT_COMPACTOR("compress");
}
#endif /* defined HAVE_COMPRESS */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the whole-size-limit option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptWhole_Size_Limit(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[2] = {
        { 8, 1023 },       { 8192, 4194304 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 2; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

 emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 2);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the split-size-limit option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptSplit_Size_Limit(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[2] = {
        { 8, 1023 },       { 8192, 4194304 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 2; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

 emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 2);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the input-file-list option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptInput_File_List(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from shar-opts.def, line 361 */
    char const * fnm = pOptDesc->optArg.argString;
    validate_opt_context (pOptions, pOptDesc);
    if (strcmp (fnm, "-") != 0) {
        FILE * fp = freopen(fnm, "r", stdin);
        if (fp != stdin)
            usage_message(_("Cannot reopen %s as stdin"), fnm);
    }
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the stdin-file-list option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptStdin_File_List(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from shar-opts.def, line 397 */
    SET_OPT_INPUT_FILE_LIST("-");
    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the vanilla-operation option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptVanilla_Operation(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from shar-opts.def, line 592 */
    validate_opt_context (pOptions, pOptDesc);

    SET_OPT_NO_CHARACTER_COUNT;
    SET_OPT_NO_TIMESTAMP;
    SET_OPT_NO_MD5_DIGEST;
    SET_OPT_NO_I18N;
    SET_OPT_NO_PIPING;
    SET_OPT_FORCE_PREFIX;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the print-text-domain-dir option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptPrint_Text_Domain_Dir(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from shar-opts.def, line 747 */
    validate_opt_context (pOptions, pOptDesc);

#if !defined ENABLE_NLS || defined HAVE_CATGETS \
    || (defined HAVE_GETTEXT && !defined __USE_GNU_GETTEXT)
    exit (EXIT_FAILURE);
#else
    puts (LOCALEDIR);
    exit (EXIT_SUCCESS);
#endif
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the silent option.
 *
 * @param pOptions the shar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptSilent(tOptions* pOptions, tOptDesc* pOptDesc)
{
    int res = optionAlias(pOptions, pOptDesc, INDEX_OPT_QUIET);
    if ((res != 0) && ((pOptions->fOptSet & OPTPROC_ERRSTOP) != 0))
        USAGE(SHAR_EXIT_USAGE_ERROR);

}
/* extracted from optmain.tlib near line 1196 */

/**
 * Print a usage message with a format and va_list argument.
 * The optionUsage function is then invoked to print
 * the error usage text (somewhat abbreviated) and then exit.
 *
 * @param[in] fmt the message format string
 * @param[in] ap  the var-arg list.
 * @noreturn
 */
void
vusage_message(char const * fmt, va_list ap)
{
    char const * er_leader = _("shar usage error:\n");
    fputs(er_leader, stderr);
    vfprintf(stderr, fmt, ap);
    optionUsage(&sharOptions, SHAR_EXIT_USAGE_ERROR);
    /* NOTREACHED */
}

/**
 * Print a usage message with a format and a variable argument list.
 * vusage_message() is called to do the work.
 *
 * @param[in] fmt the message format string
 * @param[in] ... the argument list for the message
 * @noreturn
 */
void
usage_message(char const * fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vusage_message(fmt, ap);
    /* NOTREACHED */
    va_end(ap);
}

/**
 * Print a fatal error message and die
 *
 * @param[in] exit_code  the value to call exit(3) with
 * @param[in] fmt        the death rattle message
 * @param[in] ap         the argument list for the message
 * @noreturn
 */
void
vdie(int exit_code, char const * fmt, va_list ap)
{
    char const * die_leader = _("shar fatal error:\n");
    fputs(die_leader, stderr);
    vfprintf(stderr, fmt, ap);
    fflush(stderr);
    exit(exit_code);
    /* NOTREACHED */
}

/**
 * Print a fatal error message and die
 *
 * @param[in] exit_code  the value to call exit(3) with
 * @param[in] fmt        the death rattle message
 * @param[in] ...        the list of arguments for the message
 * @noreturn
 */
void
die(int exit_code, char const * fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vdie(exit_code, fmt, ap);
    /* NOTREACHED */
    va_end(ap);
}

/**
 * Print a file system error fatal error message and die
 *
 * @param[in] exit_code  the value to call exit(3) with.
 * @param[in] op         the operation that failed.
 * @param[in] fname      the file name the operation was on.
 * @noreturn
 */
void
fserr(int exit_code, char const * op, char const * fname)
{
    char const * fserr_fmt = _("fserr %d (%s) performing '%s' on %s\n");
    die(exit_code, fserr_fmt, errno, strerror(errno), op, fname);
    /* NOTREACHED */
}

/**
 * The directory containing the data associated with shar.
 */
#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

/**
 * Information about the person or institution that packaged shar
 * for the current distribution.
 */
#ifndef  WITH_PACKAGER
# define shar_packager_info NULL
#else
static char const shar_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport shar bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif
#ifndef __doxygen__

#endif /* __doxygen__ */
/**
 * The option definitions for shar.  The one structure that
 * binds them all.
 */
tOptions sharOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_GNUUSAGE
    + OPTPROC_MISUSE ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      INDEX_OPT_SAVE_OPTS, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      NO_EQUIVALENT /* index of default opt */
    },
    49 /* full option count */, 44 /* user option count */,
    shar_full_usage, shar_short_usage,
    NULL, NULL,
    PKGDATADIR, shar_packager_info
};

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#ifdef HAVE_DCGETTEXT
# include <gettext.h>
#endif
#include <autoopts/usage-txt.h>

static char * AO_gettext(char const * pz);
static void   coerce_it(void ** s);

/**
 * AutoGen specific wrapper function for gettext.  It relies on the macro _()
 * to convert from English to the target language, then strdup-duplicates the
 * result string.  It tries the "libopts" domain first, then whatever has been
 * set via the \a textdomain(3) call.
 *
 * @param[in] pz the input text used as a lookup key.
 * @returns the translated text (if there is one),
 *   or the original text (if not).
 */
static char *
AO_gettext(char const * pz)
{
    char * res;
    if (pz == NULL)
        return NULL;
#ifdef HAVE_DCGETTEXT
    /*
     * While processing the option_xlateable_txt data, try to use the
     * "libopts" domain.  Once we switch to the option descriptor data,
     * do *not* use that domain.
     */
    if (option_xlateable_txt.field_ct != 0) {
        res = dgettext("libopts", pz);
        if (res == pz)
            res = (char *)(void *)_(pz);
    } else
        res = (char *)(void *)_(pz);
#else
    res = (char *)(void *)_(pz);
#endif
    if (res == pz)
        return res;
    res = strdup(res);
    if (res == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(SHAR_EXIT_OPTION_ERROR);
    }
    return res;
}

/**
 * All the pointers we use are marked "* const", but they are stored in
 * writable memory.  Coerce the mutability and set the pointer.
 */
static void coerce_it(void ** s) { *s = AO_gettext(*s);
}

/**
 * Translate all the translatable strings in the sharOptions
 * structure defined above.  This is done only once.
 */
static void
translate_option_strings(void)
{
    tOptions * const opts = &sharOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_xlateable_txt.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * od = opts->pOptDesc;
        char **    ppz = (char**)(void*)&(option_xlateable_txt);
        int        ix  = option_xlateable_txt.field_ct;

        do {
            ppz++; /* skip over field_ct */
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);
        /* prevent re-translation and disable "libopts" domain lookup */
        option_xlateable_txt.field_ct = 0;

        coerce_it((void*)&(opts->pzCopyright));
        coerce_it((void*)&(opts->pzCopyNotice));
        coerce_it((void*)&(opts->pzFullVersion));
        coerce_it((void*)&(opts->pzUsageTitle));
        coerce_it((void*)&(opts->pzExplain));
        coerce_it((void*)&(opts->pzDetail));
        coerce_it((void*)&(opts->pzPackager));
        coerce_it((void*)&(opts->pzFullUsage));
        coerce_it((void*)&(opts->pzShortUsage));

        for (ix = opts->optCt; ix > 0; ix--, od++)
            coerce_it((void*)&(od->pzText));
    }

    if ((opts->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * od = opts->pOptDesc;
        int        ix;

        for (ix = opts->optCt; ix > 0; ix--, od++) {
            coerce_it((void*)&(od->pz_Name));
            coerce_it((void*)&(od->pz_DisableName));
            coerce_it((void*)&(od->pz_DisablePfx));
        }
        sharOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef DO_NOT_COMPILE_THIS_CODE_IT_IS_FOR_GETTEXT
static void bogus_function(void) {

  /* prog-title */
  puts(_("create a shell archiv"));
  /* full-usage */
  puts(_("shar (GNU sharutils) - create a shell archive - Ver. 4.13.3\n\
USAGE:  shar [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [file ...]\n\n\n\
specifying compression:\n\n\
   -p, --intermix-type        specify compression for input files\n\
                                - prohibits these options:\n\
                                vanilla-operation\n\
   -C, --compactor=str        specify compaction (compression) program\n\
                                - prohibits these options:\n\
                                vanilla-operation\n\
                                - may appear multiple times\n\
   -g, --level-of-compression=num pass LEVEL for compression\n\
                                - It must be in the range:\n\
                                  1 to 9\n\
       --level-for-gzip=num   This is an alias for 'level-of-compression'\n\n\
specifying file encoding methodology:\n\n\
   -M, --mixed-uuencode       decide uuencoding for each file\n\
   -B, --uuencode             treat all files as binary\n\
                                - an alternate for mixed-uuencode\n\
   -T, --text-files           treat all files as text\n\
                                - an alternate for mixed-uuencode\n\n\
specifying file selection and output modes:\n\n\
   -o, --output-prefix=str    print output to file PREFIX.nn\n\
   -l, --whole-size-limit=num split archive, not files, to size\n\
                                - requires these options:\n\
                                output-prefix\n\
                                - is scalable with a suffix: k/K/m/M/g/G/t/T\n\
                                - It must lie in one of the ranges:\n\
                                  8 to 1023, or\n\
                                  8192 to 4194304\n\
   -L, --split-size-limit=num split archive or files to size\n\
                                - requires these options:\n\
                                output-prefix\n\
                                - is scalable with a suffix: k/K/m/M/g/G/t/T\n\
                                - It must lie in one of the ranges:\n\
                                  8 to 1023, or\n\
                                  8192 to 4194304\n\
                                - an alternate for whole-size-limit\n\
   -I, --input-file-list=str  read file list from a file\n\n\
Controlling the shar headers:\n\n\
   -n, --archive-name=str     use name to document the archive\n\
   -s, --submitter=str        override the submitter name\n\
   -a, --net-headers          output Submitted-by: & Archive-name: headers\n\
                                - requires these options:\n\
                                archive-name\n\
   -c, --cut-mark             start the shar with a cut line\n\
   -t, --translate            translate messages in the script\n\n\
Protecting against transmission issues::\n\n\
       --no-character-count   do not use `wc -c' to check size\n\
   -D, --no-md5-digest        do not use md5sum digest to verify\n\
   -F, --force-prefix         apply the prefix character on every line\n\
   -d, --here-delimiter=str   use delim to delimit the files\n\n\
Producing different kinds of shars::\n\n\
   -V, --vanilla-operation    produce very simple shars\n\
   -P, --no-piping            use temporary files between programs\n\
   -x, --no-check-existing    blindly overwrite existing files\n\
   -X, --query-user           ask user before overwriting files\n\
                                - prohibits these options:\n\
                                vanilla-operation\n\
   -m, --no-timestamp         do not restore modification times\n\
   -Q, --quiet-unshar         avoid verbose messages at unshar time\n\
   -f, --basename             restore in one directory, despite hierarchy\n\n\
Internationalization options::\n\n\
       --no-i18n              do not internationalize\n\
       --print-text-domain-dir  print directory with shar messages\n\n\
user feedback/entertainment:\n\n\
   -q, --quiet                do not output verbose messages\n\
       --silent               This is an alias for 'quiet'\n\n\
version, usage and configuration options:\n\n\
   -v, --version[=arg]        Output version information and exit\n\
   -h, --help                 Display extended usage information and exit\n\
   -!, --more-help            Extended usage information passed thru pager\n\
   -R, --save-opts[=arg]      Save the option state to a config file\n\
   -r, --load-opts=str        Load options from a config file\n\
                                - disabled as --no-load-opts\n\
                                - may appear multiple times\n\n\
Options are specified by doubled hyphens and their name or by a single\n\
hyphen and the flag character.\n\n\
If no 'file's are specified, the list of input files is read from a\n\
standard input.  Standard input must not be a terminal.\n\n\
The following option preset mechanisms are supported:\n\
 - reading file $HOME/.sharrc\n\n\
'shar' creates \"shell archives\" (or shar files) which are in text format\n\
and can be emailed.  These files may be unpacked later by executing them\n\
with '/bin/sh'.  The resulting archive is sent to standard out unless the\n\
'-o' option is given.  A wide range of features provide extensive\n\
flexibility in manufacturing shars and in specifying 'shar' \"smartness\".\n\
Archives may be fairly simple ('--vanilla-operation') or essentially a\n\
mailable 'tar' archive.\n\n\
Options may be specified in any order until a 'file' argument is\n\
recognized.  If the '--intermix-type' option has been specified, more\n\
compression and encoding options will be recognized between the 'file'\n\
arguments.\n\n\
Though this program supports 'uuencode'-d files, they are deprecated.  If\n\
you are emailing files, please consider mime-encoded files.  If you do\n\
'uuencode', base 64 is the preferred encoding method.\n\n\
please send bug reports to:  bug-gnu-utils@gnu.org"));
  /* short-usage */
  puts(_("shar (GNU sharutils) - create a shell archive - Ver. 4.13.3\n\
USAGE:  shar [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [file ...]"));
  /* explain */
  puts(_("If no 'file's are specified, the list of input files is read from a\n\
standard input.  Standard input must not be a terminal"));
  /* detail */
  puts(_("'shar' creates \"shell archives\" (or shar files) which are in text format\n\
and can be emailed.  These files may be unpacked later by executing them\n\
with '/bin/sh'.  The resulting archive is sent to standard out unless the\n\
'-o' option is given.  A wide range of features provide extensive\n\
flexibility in manufacturing shars and in specifying 'shar' \"smartness\".\n\
Archives may be fairly simple ('--vanilla-operation') or essentially a\n\
mailable 'tar' archive.\n\n\
Options may be specified in any order until a 'file' argument is\n\
recognized.  If the '--intermix-type' option has been specified, more\n\
compression and encoding options will be recognized between the 'file'\n\
arguments.\n\n\
Though this program supports 'uuencode'-d files, they are deprecated.  If\n\
you are emailing files, please consider mime-encoded files.  If you do\n\
'uuencode', base 64 is the preferred encoding method"));
  /* copyright.type */
  puts(_("This program is released under the terms of the GNU General Public License, version 3 or later."));
}
#endif /* uncompilable code */
#ifdef  __cplusplus
}
#endif
/* shar-opts.c ends here */
