/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (unshar-opts.c)
 *  
 *  It has been AutoGen-ed  January  6, 2013 at 06:21:34 PM by AutoGen 5.17.2pre2
 *  From the definitions    unshar-opts.def
 *  and the template file   options
 *
 * Generated from AutoOpts 37:1:12 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the unshar author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * The unshar program is copyrighted and licensed
 * under the following terms:
 *
 *  Copyright (C) 1994-2013 Free Software Foundation, Inc., all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *
 *  unshar is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  unshar is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __doxygen__
#define OPTION_CODE_COMPILE 1
#include "unshar-opts.h"
#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>

#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
#define zCopyright      (unshar_opt_strs+0)
#define zLicenseDescrip (unshar_opt_strs+296)

/*
 *  global included definitions
 */
#include <errno.h>
#include <error.h>
#include <unistd.h>

#ifndef NULL
#  define NULL 0
#endif

/*
 *  unshar option static const strings
 */
static char const unshar_opt_strs[2591] =
/*     0 */ "unshar (GNU sharutils) 4.13.3\n"
            "Copyright (C) 1994-2013 Free Software Foundation, Inc., all rights reserved.\n"
            "This is free software. It is licensed for use, modification and\n"
            "redistribution under the terms of the\n"
            "GNU General Public License, version 3 or later\n"
            "    <http://gnu.org/licenses/gpl.html>\n\0"
/*   296 */ "unshar is free software: you can redistribute it and/or modify it under the\n"
            "terms of the GNU General Public License as published by the Free Software\n"
            "Foundation, either version 3 of the License, or (at your option) any later\n"
            "version.\n\n"
            "unshar is distributed in the hope that it will be useful, but WITHOUT ANY\n"
            "WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS\n"
            "FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more\n"
            "details.\n\n"
            "You should have received a copy of the GNU General Public License along\n"
            "with this program.  If not, see <http://www.gnu.org/licenses/>.\n\0"
/*   897 */ "change directory to dir first\0"
/*   927 */ "DIRECTORY\0"
/*   937 */ "directory\0"
/*   947 */ "Overwrite any pre-existing files\0"
/*   980 */ "OVERWRITE\0"
/*   990 */ "overwrite\0"
/*  1000 */ "This is an alias for 'overwrite'\0"
/*  1033 */ "force\0"
/*  1039 */ "separate archives on split-pat lines\0"
/*  1076 */ "SPLIT_AT\0"
/*  1085 */ "split-at\0"
/*  1094 */ "split archives at \"exit 0\" lines\0"
/*  1127 */ "EXIT_0\0"
/*  1134 */ "exit-0\0"
/*  1141 */ "Display extended usage information and exit\0"
/*  1185 */ "help\0"
/*  1190 */ "Extended usage information passed thru pager\0"
/*  1235 */ "more-help\0"
/*  1245 */ "Output version information and exit\0"
/*  1281 */ "version\0"
/*  1289 */ "Save the option state to a config file\0"
/*  1328 */ "save-opts\0"
/*  1338 */ "Load options from a config file\0"
/*  1370 */ "LOAD_OPTS\0"
/*  1380 */ "no-load-opts\0"
/*  1393 */ "no\0"
/*  1396 */ "UNSHAR\0"
/*  1403 */ "unshar (GNU sharutils) - unpack a shar archive - Ver. 4.13.3\n"
            "USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [ file ... ]\n\0"
/*  1535 */ "$HOME\0"
/*  1541 */ ".sharrc\0"
/*  1549 */ "bug-gnu-utils@gnu.org\0"
/*  1571 */ "\n"
            "Unshar scans the input files (typically email messages) looking for the\n"
            "start of a shell archive.  If no files are given, then standard input is\n"
            "processed instead.  It then passes each archive discovered through an\n"
            "invocation of the shell program to unpack it.\n\0"
/*  1834 */ "unshar (GNU sharutils) 4.13.3\0"
/*  1864 */ "Usage: ./unshar [OPTION]... [FILE]...\n"
            "Mandatory arguments to long options are mandatory for short options too.\n\n"
            "  -d, --directory=DIRECTORY   change to DIRECTORY before unpacking\n"
            "  -c, --overwrite             pass -c to shar script for overwriting files\n"
            "  -e, --exit-0                same as `--split-at=\"exit 0\"'\n"
            "  -E, --split-at=STRING       split concatenated shars after STRING\n"
            "  -f, --force                 same as `-c'\n"
            "      --help                  display this help and exit\n"
            "      --version               output version information and exit\n\n"
            "If no FILE, standard input is read.\n"
            "Report bugs to <bug-gnu-utils@gnu.org>.\0"
/*  2489 */ "./unshar: unrecognized option '--error-bogus-option-name'\n"
            "Try `./unshar --help' for more information.";

/*
 *  directory option description:
 */
#define DIRECTORY_DESC      (unshar_opt_strs+897)
#define DIRECTORY_NAME      (unshar_opt_strs+927)
#define DIRECTORY_name      (unshar_opt_strs+937)
#define DIRECTORY_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  overwrite option description:
 */
#define OVERWRITE_DESC      (unshar_opt_strs+947)
#define OVERWRITE_NAME      (unshar_opt_strs+980)
#define OVERWRITE_name      (unshar_opt_strs+990)
#define OVERWRITE_FLAGS     (OPTST_DISABLED)

/*
 *  force option description:
 */
#define FORCE_DESC    (unshar_opt_strs+1000)
#define FORCE_NAME    NULL
#define FORCE_name    (unshar_opt_strs+1033)
#define FORCE_FLAGS     (OVERWRITE_FLAGS | OPTST_ALIAS)

/*
 *  split-at option description:
 */
#define SPLIT_AT_DESC      (unshar_opt_strs+1039)
#define SPLIT_AT_NAME      (unshar_opt_strs+1076)
#define SPLIT_AT_name      (unshar_opt_strs+1085)
#define SPLIT_AT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  exit-0 option description with
 *  "Must also have options" and "Incompatible options":
 */
#define EXIT_0_DESC      (unshar_opt_strs+1094)
#define EXIT_0_NAME      (unshar_opt_strs+1127)
#define EXIT_0_name      (unshar_opt_strs+1134)
static int const aExit_0CantList[] = {
    INDEX_OPT_SPLIT_AT, NO_EQUIVALENT };
#define EXIT_0_FLAGS     (OPTST_DISABLED)

/*
 *  Help/More_Help/Version option descriptions:
 */
#define HELP_DESC       (unshar_opt_strs+1141)
#define HELP_name       (unshar_opt_strs+1185)
#ifdef HAVE_WORKING_FORK
#define MORE_HELP_DESC  (unshar_opt_strs+1190)
#define MORE_HELP_name  (unshar_opt_strs+1235)
#define MORE_HELP_FLAGS (OPTST_IMM | OPTST_NO_INIT)
#else
#define MORE_HELP_DESC  NULL
#define MORE_HELP_name  NULL
#define MORE_HELP_FLAGS (OPTST_OMITTED | OPTST_NO_INIT)
#endif
#ifdef NO_OPTIONAL_OPT_ARGS
#  define VER_FLAGS     (OPTST_IMM | OPTST_NO_INIT)
#else
#  define VER_FLAGS     (OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | \
                         OPTST_ARG_OPTIONAL | OPTST_IMM | OPTST_NO_INIT)
#endif
#define VER_DESC        (unshar_opt_strs+1245)
#define VER_name        (unshar_opt_strs+1281)
#define SAVE_OPTS_DESC  (unshar_opt_strs+1289)
#define SAVE_OPTS_name  (unshar_opt_strs+1328)
#define LOAD_OPTS_DESC     (unshar_opt_strs+1338)
#define LOAD_OPTS_NAME     (unshar_opt_strs+1370)
#define NO_LOAD_OPTS_name  (unshar_opt_strs+1380)
#define LOAD_OPTS_pfx      (unshar_opt_strs+1393)
#define LOAD_OPTS_name     (NO_LOAD_OPTS_name + 3)
/*
 *  Declare option callback procedures
 */
extern tOptProc
    optionBooleanVal,   optionNestedVal,    optionNumericVal,
    optionPagedUsage,   optionPrintVersion, optionResetOpt,
    optionStackArg,     optionTimeDate,     optionTimeVal,
    optionUnstackArg,   optionVendorOption;
static tOptProc
    doOptDirectory, doOptExit_0, doOptForce, doUsageOpt;
#define VER_PROC        optionPrintVersion

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 *  Define the unshar Option Descriptions.
 * This is an array of OPTION_CT entries, one for each
 * option that the unshar program responds to.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, VALUE_OPT_DIRECTORY,
     /* equiv idx, value */ 0, VALUE_OPT_DIRECTORY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DIRECTORY_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --directory */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptDirectory,
     /* desc, NAME, name */ DIRECTORY_DESC, DIRECTORY_NAME, DIRECTORY_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_OVERWRITE,
     /* equiv idx, value */ 1, VALUE_OPT_OVERWRITE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OVERWRITE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --overwrite */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ OVERWRITE_DESC, OVERWRITE_NAME, OVERWRITE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_FORCE,
     /* equiv idx, value */ 2, VALUE_OPT_FORCE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FORCE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --force */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptForce,
     /* desc, NAME, name */ FORCE_DESC, FORCE_NAME, FORCE_name,
     /* disablement strs */ 0, 0 },

  {  /* entry idx, value */ 3, VALUE_OPT_SPLIT_AT,
     /* equiv idx, value */ 3, VALUE_OPT_SPLIT_AT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SPLIT_AT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --split-at */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SPLIT_AT_DESC, SPLIT_AT_NAME, SPLIT_AT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_EXIT_0,
     /* equiv idx, value */ 4, VALUE_OPT_EXIT_0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ EXIT_0_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --exit-0 */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aExit_0CantList,
     /* option proc      */ doOptExit_0,
     /* desc, NAME, name */ EXIT_0_DESC, EXIT_0_NAME, EXIT_0_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_VERSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VER_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ VER_PROC,
     /* desc, NAME, name */ VER_DESC, NULL, VER_name,
     /* disablement strs */ NULL, NULL },



  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ HELP_DESC, NULL, HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_MORE_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ MORE_HELP_DESC, NULL, MORE_HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_SAVE_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SAVE_OPTS_DESC, NULL, SAVE_OPTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_LOAD_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
			  | OPTST_DISABLE_IMM, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionLoadOpt,
     /* desc, NAME, name */ LOAD_OPTS_DESC, LOAD_OPTS_NAME, LOAD_OPTS_name,
     /* disablement strs */ NO_LOAD_OPTS_name, LOAD_OPTS_pfx }
};


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the unshar Option Environment
 */
#define zPROGNAME       (unshar_opt_strs+1396)
#define zUsageTitle     (unshar_opt_strs+1403)
#define zRcName         (unshar_opt_strs+1541)
static char const * const apzHomeList[2] = {
    unshar_opt_strs+1535,
    NULL };
#define zBugsAddr       (unshar_opt_strs+1549)
#define zExplain        (NULL)
#define zDetail         (unshar_opt_strs+1571)
#define zFullVersion    (unshar_opt_strs+1834)
/* extracted from optcode.tlib near line 353 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */


#define unshar_full_usage (unshar_opt_strs+1864)

#define unshar_short_usage (unshar_opt_strs+2489)

#endif /* not defined __doxygen__ */

/*
 *  Create the static procedure(s) declared above.
 */
/**
 * The callout function that invokes the optionUsage function.
 *
 * @param pOptions the AutoOpts option description structure
 * @param pOptDesc the descriptor for the "help" (usage) option.
 * @noreturn
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    optionUsage(&unsharOptions, UNSHAR_EXIT_SUCCESS);
    /* NOTREACHED */
    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the directory option.
 *
 * @param pOptions the unshar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptDirectory(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from unshar-opts.def, line 32 */
  int res = chdir (pOptDesc->optArg.argString);
  if (res == -1)
    {
      error (2, 0, _("Cannot chdir to `%s'"),
             pOptDesc->optArg.argString);
      USAGE(UNSHAR_EXIT_FAILURE);
    }
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the force option.
 *
 * @param pOptions the unshar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptForce(tOptions* pOptions, tOptDesc* pOptDesc)
{
    int res = optionAlias(pOptions, pOptDesc, INDEX_OPT_OVERWRITE);
    if ((res != 0) && ((pOptions->fOptSet & OPTPROC_ERRSTOP) != 0))
        USAGE(UNSHAR_EXIT_USAGE_ERROR);

}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the exit-0 option.
 *
 * @param pOptions the unshar options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptExit_0(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from unshar-opts.def, line 89 */
  SET_OPT_SPLIT_AT("exit 0");
    (void)pOptDesc;
    (void)pOptions;
}
/* extracted from optmain.tlib near line 1196 */

/**
 * Print a usage message with a format and va_list argument.
 * The optionUsage function is then invoked to print
 * the error usage text (somewhat abbreviated) and then exit.
 *
 * @param[in] fmt the message format string
 * @param[in] ap  the var-arg list.
 * @noreturn
 */
void
vusage_message(char const * fmt, va_list ap)
{
    char const * er_leader = _("unshar usage error:\n");
    fputs(er_leader, stderr);
    vfprintf(stderr, fmt, ap);
    optionUsage(&unsharOptions, UNSHAR_EXIT_USAGE_ERROR);
    /* NOTREACHED */
}

/**
 * Print a usage message with a format and a variable argument list.
 * vusage_message() is called to do the work.
 *
 * @param[in] fmt the message format string
 * @param[in] ... the argument list for the message
 * @noreturn
 */
void
usage_message(char const * fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vusage_message(fmt, ap);
    /* NOTREACHED */
    va_end(ap);
}

/**
 * Print a fatal error message and die
 *
 * @param[in] exit_code  the value to call exit(3) with
 * @param[in] fmt        the death rattle message
 * @param[in] ap         the argument list for the message
 * @noreturn
 */
void
vdie(int exit_code, char const * fmt, va_list ap)
{
    char const * die_leader = _("unshar fatal error:\n");
    fputs(die_leader, stderr);
    vfprintf(stderr, fmt, ap);
    fflush(stderr);
    exit(exit_code);
    /* NOTREACHED */
}

/**
 * Print a fatal error message and die
 *
 * @param[in] exit_code  the value to call exit(3) with
 * @param[in] fmt        the death rattle message
 * @param[in] ...        the list of arguments for the message
 * @noreturn
 */
void
die(int exit_code, char const * fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vdie(exit_code, fmt, ap);
    /* NOTREACHED */
    va_end(ap);
}

/**
 * Print a file system error fatal error message and die
 *
 * @param[in] exit_code  the value to call exit(3) with.
 * @param[in] op         the operation that failed.
 * @param[in] fname      the file name the operation was on.
 * @noreturn
 */
void
fserr(int exit_code, char const * op, char const * fname)
{
    char const * fserr_fmt = _("fserr %d (%s) performing '%s' on %s\n");
    die(exit_code, fserr_fmt, errno, strerror(errno), op, fname);
    /* NOTREACHED */
}

/**
 * The directory containing the data associated with unshar.
 */
#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

/**
 * Information about the person or institution that packaged unshar
 * for the current distribution.
 */
#ifndef  WITH_PACKAGER
# define unshar_packager_info NULL
#else
static char const unshar_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport unshar bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif
#ifndef __doxygen__

#endif /* __doxygen__ */
/**
 * The option definitions for unshar.  The one structure that
 * binds them all.
 */
tOptions unsharOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_GNUUSAGE
    + OPTPROC_MISUSE ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      INDEX_OPT_SAVE_OPTS, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      NO_EQUIVALENT /* index of default opt */
    },
    10 /* full option count */, 5 /* user option count */,
    unshar_full_usage, unshar_short_usage,
    NULL, NULL,
    PKGDATADIR, unshar_packager_info
};

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#ifdef HAVE_DCGETTEXT
# include <gettext.h>
#endif
#include <autoopts/usage-txt.h>

static char * AO_gettext(char const * pz);
static void   coerce_it(void ** s);

/**
 * AutoGen specific wrapper function for gettext.  It relies on the macro _()
 * to convert from English to the target language, then strdup-duplicates the
 * result string.  It tries the "libopts" domain first, then whatever has been
 * set via the \a textdomain(3) call.
 *
 * @param[in] pz the input text used as a lookup key.
 * @returns the translated text (if there is one),
 *   or the original text (if not).
 */
static char *
AO_gettext(char const * pz)
{
    char * res;
    if (pz == NULL)
        return NULL;
#ifdef HAVE_DCGETTEXT
    /*
     * While processing the option_xlateable_txt data, try to use the
     * "libopts" domain.  Once we switch to the option descriptor data,
     * do *not* use that domain.
     */
    if (option_xlateable_txt.field_ct != 0) {
        res = dgettext("libopts", pz);
        if (res == pz)
            res = (char *)(void *)_(pz);
    } else
        res = (char *)(void *)_(pz);
#else
    res = (char *)(void *)_(pz);
#endif
    if (res == pz)
        return res;
    res = strdup(res);
    if (res == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(UNSHAR_EXIT_FAILURE);
    }
    return res;
}

/**
 * All the pointers we use are marked "* const", but they are stored in
 * writable memory.  Coerce the mutability and set the pointer.
 */
static void coerce_it(void ** s) { *s = AO_gettext(*s);
}

/**
 * Translate all the translatable strings in the unsharOptions
 * structure defined above.  This is done only once.
 */
static void
translate_option_strings(void)
{
    tOptions * const opts = &unsharOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_xlateable_txt.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * od = opts->pOptDesc;
        char **    ppz = (char**)(void*)&(option_xlateable_txt);
        int        ix  = option_xlateable_txt.field_ct;

        do {
            ppz++; /* skip over field_ct */
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);
        /* prevent re-translation and disable "libopts" domain lookup */
        option_xlateable_txt.field_ct = 0;

        coerce_it((void*)&(opts->pzCopyright));
        coerce_it((void*)&(opts->pzCopyNotice));
        coerce_it((void*)&(opts->pzFullVersion));
        coerce_it((void*)&(opts->pzUsageTitle));
        coerce_it((void*)&(opts->pzExplain));
        coerce_it((void*)&(opts->pzDetail));
        coerce_it((void*)&(opts->pzPackager));
        coerce_it((void*)&(opts->pzFullUsage));
        coerce_it((void*)&(opts->pzShortUsage));

        for (ix = opts->optCt; ix > 0; ix--, od++)
            coerce_it((void*)&(od->pzText));
    }

    if ((opts->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * od = opts->pOptDesc;
        int        ix;

        for (ix = opts->optCt; ix > 0; ix--, od++) {
            coerce_it((void*)&(od->pz_Name));
            coerce_it((void*)&(od->pz_DisableName));
            coerce_it((void*)&(od->pz_DisablePfx));
        }
        unsharOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef DO_NOT_COMPILE_THIS_CODE_IT_IS_FOR_GETTEXT
static void bogus_function(void) {

  /* prog-title */
  puts(_("unpack a shar archiv"));
  /* full-usage */
  puts(_("Usage: ./unshar [OPTION]... [FILE]...\n\
Mandatory arguments to long options are mandatory for short options too.\n\n\
  -d, --directory=DIRECTORY   change to DIRECTORY before unpacking\n\
  -c, --overwrite             pass -c to shar script for overwriting files\n\
  -e, --exit-0                same as `--split-at=\"exit 0\"'\n\
  -E, --split-at=STRING       split concatenated shars after STRING\n\
  -f, --force                 same as `-c'\n\
      --help                  display this help and exit\n\
      --version               output version information and exit\n\n\
If no FILE, standard input is read.\n\
Report bugs to <bug-gnu-utils@gnu.org>."));
  /* short-usage */
  puts(_("./unshar: unrecognized option '--error-bogus-option-name'\n\
Try `./unshar --help' for more information."));
  /* detail */
  puts(_("Unshar scans the input files (typically email messages) looking for the\n\
start of a shell archive.  If no files are given, then standard input is\n\
processed instead.  It then passes each archive discovered through an\n\
invocation of the shell program to unpack it"));
  /* copyright.type */
  puts(_("This program is released under the terms of the GNU General Public License, version 3 or later."));
}
#endif /* uncompilable code */
#ifdef  __cplusplus
}
#endif
/* unshar-opts.c ends here */
