/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (uuencode-opts.c)
 *  
 *  It has been AutoGen-ed  January  6, 2013 at 06:21:42 PM by AutoGen 5.17.2pre2
 *  From the definitions    uuencode-opts.def
 *  and the template file   options
 *
 * Generated from AutoOpts 37:1:12 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the uuencode author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * The uuencode program is copyrighted and licensed
 * under the following terms:
 *
 *  Copyright (C) 1994-2013 Free Software Foundation, Inc., all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *
 *  uuencode is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  uuencode is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __doxygen__
#define OPTION_CODE_COMPILE 1
#include "uuencode-opts.h"
#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>

#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
#define zCopyright      (uuencode_opt_strs+0)
#define zLicenseDescrip (uuencode_opt_strs+298)

/*
 *  global included definitions
 */
extern char const * trans_ptr;
extern char const uu_base64[64];

#ifndef NULL
#  define NULL 0
#endif

/*
 *  uuencode option static const strings
 */
static char const uuencode_opt_strs[4248] =
/*     0 */ "uuencode (GNU sharutils) 4.13.3\n"
            "Copyright (C) 1994-2013 Free Software Foundation, Inc., all rights reserved.\n"
            "This is free software. It is licensed for use, modification and\n"
            "redistribution under the terms of the\n"
            "GNU General Public License, version 3 or later\n"
            "    <http://gnu.org/licenses/gpl.html>\n\0"
/*   298 */ "uuencode is free software: you can redistribute it and/or modify it under\n"
            "the terms of the GNU General Public License as published by the Free\n"
            "Software Foundation, either version 3 of the License, or (at your option)\n"
            "any later version.\n\n"
            "uuencode is distributed in the hope that it will be useful, but WITHOUT ANY\n"
            "WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS\n"
            "FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more\n"
            "details.\n\n"
            "You should have received a copy of the GNU General Public License along\n"
            "with this program.  If not, see <http://www.gnu.org/licenses/>.\n\0"
/*   903 */ "convert using base 64\0"
/*   925 */ "BASE64\0"
/*   932 */ "base64\0"
/*   939 */ "encode the output file name\0"
/*   967 */ "ENCODE_FILE_NAME\0"
/*   984 */ "encode-file-name\0"
/*  1001 */ "Display extended usage information and exit\0"
/*  1045 */ "help\0"
/*  1050 */ "Extended usage information passed thru pager\0"
/*  1095 */ "more-help\0"
/*  1105 */ "Output version information and exit\0"
/*  1141 */ "version\0"
/*  1149 */ "Save the option state to a config file\0"
/*  1188 */ "save-opts\0"
/*  1198 */ "Load options from a config file\0"
/*  1230 */ "LOAD_OPTS\0"
/*  1240 */ "no-load-opts\0"
/*  1253 */ "no\0"
/*  1256 */ "UUENCODE\0"
/*  1265 */ "uuencode (GNU sharutils) - encode a file into email friendly text - Ver. 4.13.3\n"
            "USAGE:  %s [ -<flag> | --<name> ]... [ in-file ] output-name\n\0"
/*  1407 */ "$HOME\0"
/*  1413 */ ".sharrc\0"
/*  1421 */ "bug-gnu-utils@gnu.org\0"
/*  1443 */ "\n"
            "'uuencode' is used to create an ASCII representation of a file that can be\n"
            "sent over channels that may otherwise corrupt the data.  Specifically,\n"
            "email cannot handle binary data and will often even insert a character when\n"
            "the six character sequence \"\\nFrom \" is seen.\n\n"
            "'uuencode' will read 'in-file' if provided and otherwise read data from\n"
            "standard in and write the encoded form to standard out.  The output will\n"
            "begin with a header line for use by 'uudecode' giving it the resulting\n"
            "suggested file 'output-name' and access mode.  If the 'output-name' is\n"
            "specifically '/dev/stdout', then 'uudecode' will emit the decoded file to\n"
            "standard out.\n\n"
            "'Note': 'uuencode' uses buffered input and assumes that it is not hand\n"
            "typed from a tty.  The consequence is that at a tty, you may need to hit\n"
            "Ctl-D several times to terminate input.\n\0"
/*  2274 */ "uuencode (GNU sharutils) 4.13.3\0"
/*  2306 */ "uuencode (GNU sharutils) - encode a file into email friendly text - Ver. 4.13.3\n"
            "USAGE:  uuencode [ -<flag> | --<name> ]... [ in-file ] output-name\n\n"
            "   -m, --base64               convert using base 64\n"
            "   -e, --encode-file-name     encode the output file name\n"
            "   -v, --version[=arg]        Output version information and exit\n"
            "   -h, --help                 Display extended usage information and exit\n"
            "   -!, --more-help            Extended usage information passed thru pager\n"
            "   -R, --save-opts[=arg]      Save the option state to a config file\n"
            "   -r, --load-opts=str        Load options from a config file\n"
            "                                - disabled as --no-load-opts\n"
            "                                - may appear multiple times\n\n"
            "Options are specified by doubled hyphens and their name or by a single\n"
            "hyphen and the flag character.\n\n"
            "The following option preset mechanisms are supported:\n"
            " - reading file $HOME/.sharrc\n\n"
            "'uuencode' is used to create an ASCII representation of a file that can be\n"
            "sent over channels that may otherwise corrupt the data.  Specifically,\n"
            "email cannot handle binary data and will often even insert a character when\n"
            "the six character sequence \"\\nFrom \" is seen.\n\n"
            "'uuencode' will read 'in-file' if provided and otherwise read data from\n"
            "standard in and write the encoded form to standard out.  The output will\n"
            "begin with a header line for use by 'uudecode' giving it the resulting\n"
            "suggested file 'output-name' and access mode.  If the 'output-name' is\n"
            "specifically '/dev/stdout', then 'uudecode' will emit the decoded file to\n"
            "standard out.\n\n"
            "'Note': 'uuencode' uses buffered input and assumes that it is not hand\n"
            "typed from a tty.  The consequence is that at a tty, you may need to hit\n"
            "Ctl-D several times to terminate input.\n\n"
            "please send bug reports to:  bug-gnu-utils@gnu.org\0"
/*  4101 */ "uuencode (GNU sharutils) - encode a file into email friendly text - Ver. 4.13.3\n"
            "USAGE:  uuencode [ -<flag> | --<name> ]... [ in-file ] output-name";

/*
 *  base64 option description:
 */
#define BASE64_DESC      (uuencode_opt_strs+903)
#define BASE64_NAME      (uuencode_opt_strs+925)
#define BASE64_name      (uuencode_opt_strs+932)
#define BASE64_FLAGS     (OPTST_DISABLED)

/*
 *  encode-file-name option description:
 */
#define ENCODE_FILE_NAME_DESC      (uuencode_opt_strs+939)
#define ENCODE_FILE_NAME_NAME      (uuencode_opt_strs+967)
#define ENCODE_FILE_NAME_name      (uuencode_opt_strs+984)
#define ENCODE_FILE_NAME_FLAGS     (OPTST_DISABLED)

/*
 *  Help/More_Help/Version option descriptions:
 */
#define HELP_DESC       (uuencode_opt_strs+1001)
#define HELP_name       (uuencode_opt_strs+1045)
#ifdef HAVE_WORKING_FORK
#define MORE_HELP_DESC  (uuencode_opt_strs+1050)
#define MORE_HELP_name  (uuencode_opt_strs+1095)
#define MORE_HELP_FLAGS (OPTST_IMM | OPTST_NO_INIT)
#else
#define MORE_HELP_DESC  NULL
#define MORE_HELP_name  NULL
#define MORE_HELP_FLAGS (OPTST_OMITTED | OPTST_NO_INIT)
#endif
#ifdef NO_OPTIONAL_OPT_ARGS
#  define VER_FLAGS     (OPTST_IMM | OPTST_NO_INIT)
#else
#  define VER_FLAGS     (OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | \
                         OPTST_ARG_OPTIONAL | OPTST_IMM | OPTST_NO_INIT)
#endif
#define VER_DESC        (uuencode_opt_strs+1105)
#define VER_name        (uuencode_opt_strs+1141)
#define SAVE_OPTS_DESC  (uuencode_opt_strs+1149)
#define SAVE_OPTS_name  (uuencode_opt_strs+1188)
#define LOAD_OPTS_DESC     (uuencode_opt_strs+1198)
#define LOAD_OPTS_NAME     (uuencode_opt_strs+1230)
#define NO_LOAD_OPTS_name  (uuencode_opt_strs+1240)
#define LOAD_OPTS_pfx      (uuencode_opt_strs+1253)
#define LOAD_OPTS_name     (NO_LOAD_OPTS_name + 3)
/*
 *  Declare option callback procedures
 */
extern tOptProc
    optionBooleanVal,   optionNestedVal,    optionNumericVal,
    optionPagedUsage,   optionPrintVersion, optionResetOpt,
    optionStackArg,     optionTimeDate,     optionTimeVal,
    optionUnstackArg,   optionVendorOption;
static tOptProc
    doOptBase64, doUsageOpt;
#define VER_PROC        optionPrintVersion

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 *  Define the uuencode Option Descriptions.
 * This is an array of OPTION_CT entries, one for each
 * option that the uuencode program responds to.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, VALUE_OPT_BASE64,
     /* equiv idx, value */ 0, VALUE_OPT_BASE64,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ BASE64_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --base64 */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptBase64,
     /* desc, NAME, name */ BASE64_DESC, BASE64_NAME, BASE64_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_ENCODE_FILE_NAME,
     /* equiv idx, value */ 1, VALUE_OPT_ENCODE_FILE_NAME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENCODE_FILE_NAME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --encode-file-name */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENCODE_FILE_NAME_DESC, ENCODE_FILE_NAME_NAME, ENCODE_FILE_NAME_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_VERSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VER_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ VER_PROC,
     /* desc, NAME, name */ VER_DESC, NULL, VER_name,
     /* disablement strs */ NULL, NULL },



  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ HELP_DESC, NULL, HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_MORE_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ MORE_HELP_DESC, NULL, MORE_HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_SAVE_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SAVE_OPTS_DESC, NULL, SAVE_OPTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_LOAD_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
			  | OPTST_DISABLE_IMM, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionLoadOpt,
     /* desc, NAME, name */ LOAD_OPTS_DESC, LOAD_OPTS_NAME, LOAD_OPTS_name,
     /* disablement strs */ NO_LOAD_OPTS_name, LOAD_OPTS_pfx }
};


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the uuencode Option Environment
 */
#define zPROGNAME       (uuencode_opt_strs+1256)
#define zUsageTitle     (uuencode_opt_strs+1265)
#define zRcName         (uuencode_opt_strs+1413)
static char const * const apzHomeList[2] = {
    uuencode_opt_strs+1407,
    NULL };
#define zBugsAddr       (uuencode_opt_strs+1421)
#define zExplain        (NULL)
#define zDetail         (uuencode_opt_strs+1443)
#define zFullVersion    (uuencode_opt_strs+2274)
/* extracted from optcode.tlib near line 353 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */


#define uuencode_full_usage (uuencode_opt_strs+2306)

#define uuencode_short_usage (uuencode_opt_strs+4101)

#endif /* not defined __doxygen__ */

/*
 *  Create the static procedure(s) declared above.
 */
/**
 * The callout function that invokes the optionUsage function.
 *
 * @param pOptions the AutoOpts option description structure
 * @param pOptDesc the descriptor for the "help" (usage) option.
 * @noreturn
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    optionUsage(&uuencodeOptions, UUENCODE_EXIT_SUCCESS);
    /* NOTREACHED */
    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the base64 option.
 *
 * @param pOptions the uuencode options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptBase64(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /*
     * Be sure the flag-code[0] handles special values for the options pointer
     * viz. (poptions <= OPTPROC_EMIT_LIMIT) *and also* the special flag bit
     * ((poptdesc->fOptState & OPTST_RESET) != 0) telling the option to
     * reset its state.
     */
    /* extracted from uuencode-opts.def, line 50 */
    trans_ptr = uu_base64;
    (void)pOptDesc;
    (void)pOptions;
}
/* extracted from optmain.tlib near line 1196 */

/**
 * Print a usage message with a format and va_list argument.
 * The optionUsage function is then invoked to print
 * the error usage text (somewhat abbreviated) and then exit.
 *
 * @param[in] fmt the message format string
 * @param[in] ap  the var-arg list.
 * @noreturn
 */
void
vusage_message(char const * fmt, va_list ap)
{
    char const * er_leader = _("uuencode usage error:\n");
    fputs(er_leader, stderr);
    vfprintf(stderr, fmt, ap);
    optionUsage(&uuencodeOptions, UUENCODE_EXIT_USAGE_ERROR);
    /* NOTREACHED */
}

/**
 * Print a usage message with a format and a variable argument list.
 * vusage_message() is called to do the work.
 *
 * @param[in] fmt the message format string
 * @param[in] ... the argument list for the message
 * @noreturn
 */
void
usage_message(char const * fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vusage_message(fmt, ap);
    /* NOTREACHED */
    va_end(ap);
}

/**
 * Print a fatal error message and die
 *
 * @param[in] exit_code  the value to call exit(3) with
 * @param[in] fmt        the death rattle message
 * @param[in] ap         the argument list for the message
 * @noreturn
 */
void
vdie(int exit_code, char const * fmt, va_list ap)
{
    char const * die_leader = _("uuencode fatal error:\n");
    fputs(die_leader, stderr);
    vfprintf(stderr, fmt, ap);
    fflush(stderr);
    exit(exit_code);
    /* NOTREACHED */
}

/**
 * Print a fatal error message and die
 *
 * @param[in] exit_code  the value to call exit(3) with
 * @param[in] fmt        the death rattle message
 * @param[in] ...        the list of arguments for the message
 * @noreturn
 */
void
die(int exit_code, char const * fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vdie(exit_code, fmt, ap);
    /* NOTREACHED */
    va_end(ap);
}

/**
 * Print a file system error fatal error message and die
 *
 * @param[in] exit_code  the value to call exit(3) with.
 * @param[in] op         the operation that failed.
 * @param[in] fname      the file name the operation was on.
 * @noreturn
 */
void
fserr(int exit_code, char const * op, char const * fname)
{
    char const * fserr_fmt = _("fserr %d (%s) performing '%s' on %s\n");
    die(exit_code, fserr_fmt, errno, strerror(errno), op, fname);
    /* NOTREACHED */
}

/**
 * The directory containing the data associated with uuencode.
 */
#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

/**
 * Information about the person or institution that packaged uuencode
 * for the current distribution.
 */
#ifndef  WITH_PACKAGER
# define uuencode_packager_info NULL
#else
static char const uuencode_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport uuencode bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif
#ifndef __doxygen__

#endif /* __doxygen__ */
/**
 * The option definitions for uuencode.  The one structure that
 * binds them all.
 */
tOptions uuencodeOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_GNUUSAGE
    + OPTPROC_MISUSE ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      INDEX_OPT_SAVE_OPTS, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      NO_EQUIVALENT /* index of default opt */
    },
    7 /* full option count */, 2 /* user option count */,
    uuencode_full_usage, uuencode_short_usage,
    NULL, NULL,
    PKGDATADIR, uuencode_packager_info
};

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#ifdef HAVE_DCGETTEXT
# include <gettext.h>
#endif
#include <autoopts/usage-txt.h>

static char * AO_gettext(char const * pz);
static void   coerce_it(void ** s);

/**
 * AutoGen specific wrapper function for gettext.  It relies on the macro _()
 * to convert from English to the target language, then strdup-duplicates the
 * result string.  It tries the "libopts" domain first, then whatever has been
 * set via the \a textdomain(3) call.
 *
 * @param[in] pz the input text used as a lookup key.
 * @returns the translated text (if there is one),
 *   or the original text (if not).
 */
static char *
AO_gettext(char const * pz)
{
    char * res;
    if (pz == NULL)
        return NULL;
#ifdef HAVE_DCGETTEXT
    /*
     * While processing the option_xlateable_txt data, try to use the
     * "libopts" domain.  Once we switch to the option descriptor data,
     * do *not* use that domain.
     */
    if (option_xlateable_txt.field_ct != 0) {
        res = dgettext("libopts", pz);
        if (res == pz)
            res = (char *)(void *)_(pz);
    } else
        res = (char *)(void *)_(pz);
#else
    res = (char *)(void *)_(pz);
#endif
    if (res == pz)
        return res;
    res = strdup(res);
    if (res == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(UUENCODE_EXIT_FAILURE);
    }
    return res;
}

/**
 * All the pointers we use are marked "* const", but they are stored in
 * writable memory.  Coerce the mutability and set the pointer.
 */
static void coerce_it(void ** s) { *s = AO_gettext(*s);
}

/**
 * Translate all the translatable strings in the uuencodeOptions
 * structure defined above.  This is done only once.
 */
static void
translate_option_strings(void)
{
    tOptions * const opts = &uuencodeOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_xlateable_txt.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * od = opts->pOptDesc;
        char **    ppz = (char**)(void*)&(option_xlateable_txt);
        int        ix  = option_xlateable_txt.field_ct;

        do {
            ppz++; /* skip over field_ct */
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);
        /* prevent re-translation and disable "libopts" domain lookup */
        option_xlateable_txt.field_ct = 0;

        coerce_it((void*)&(opts->pzCopyright));
        coerce_it((void*)&(opts->pzCopyNotice));
        coerce_it((void*)&(opts->pzFullVersion));
        coerce_it((void*)&(opts->pzUsageTitle));
        coerce_it((void*)&(opts->pzExplain));
        coerce_it((void*)&(opts->pzDetail));
        coerce_it((void*)&(opts->pzPackager));
        coerce_it((void*)&(opts->pzFullUsage));
        coerce_it((void*)&(opts->pzShortUsage));

        for (ix = opts->optCt; ix > 0; ix--, od++)
            coerce_it((void*)&(od->pzText));
    }

    if ((opts->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * od = opts->pOptDesc;
        int        ix;

        for (ix = opts->optCt; ix > 0; ix--, od++) {
            coerce_it((void*)&(od->pz_Name));
            coerce_it((void*)&(od->pz_DisableName));
            coerce_it((void*)&(od->pz_DisablePfx));
        }
        uuencodeOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef DO_NOT_COMPILE_THIS_CODE_IT_IS_FOR_GETTEXT
static void bogus_function(void) {

  /* prog-title */
  puts(_("encode a file into email friendly tex"));
  /* full-usage */
  puts(_("uuencode (GNU sharutils) - encode a file into email friendly text - Ver. 4.13.3\n\
USAGE:  uuencode [ -<flag> | --<name> ]... [ in-file ] output-name\n\n\
   -m, --base64               convert using base 64\n\
   -e, --encode-file-name     encode the output file name\n\
   -v, --version[=arg]        Output version information and exit\n\
   -h, --help                 Display extended usage information and exit\n\
   -!, --more-help            Extended usage information passed thru pager\n\
   -R, --save-opts[=arg]      Save the option state to a config file\n\
   -r, --load-opts=str        Load options from a config file\n\
                                - disabled as --no-load-opts\n\
                                - may appear multiple times\n\n\
Options are specified by doubled hyphens and their name or by a single\n\
hyphen and the flag character.\n\n\
The following option preset mechanisms are supported:\n\
 - reading file $HOME/.sharrc\n\n\
'uuencode' is used to create an ASCII representation of a file that can be\n\
sent over channels that may otherwise corrupt the data.  Specifically,\n\
email cannot handle binary data and will often even insert a character when\n\
the six character sequence \"\\nFrom \" is seen.\n\n\
'uuencode' will read 'in-file' if provided and otherwise read data from\n\
standard in and write the encoded form to standard out.  The output will\n\
begin with a header line for use by 'uudecode' giving it the resulting\n\
suggested file 'output-name' and access mode.  If the 'output-name' is\n\
specifically '/dev/stdout', then 'uudecode' will emit the decoded file to\n\
standard out.\n\n\
'Note': 'uuencode' uses buffered input and assumes that it is not hand\n\
typed from a tty.  The consequence is that at a tty, you may need to hit\n\
Ctl-D several times to terminate input.\n\n\
please send bug reports to:  bug-gnu-utils@gnu.org"));
  /* short-usage */
  puts(_("uuencode (GNU sharutils) - encode a file into email friendly text - Ver. 4.13.3\n\
USAGE:  uuencode [ -<flag> | --<name> ]... [ in-file ] output-name"));
  /* detail */
  puts(_("'uuencode' is used to create an ASCII representation of a file that can be\n\
sent over channels that may otherwise corrupt the data.  Specifically,\n\
email cannot handle binary data and will often even insert a character when\n\
the six character sequence \"\\nFrom \" is seen.\n\n\
'uuencode' will read 'in-file' if provided and otherwise read data from\n\
standard in and write the encoded form to standard out.  The output will\n\
begin with a header line for use by 'uudecode' giving it the resulting\n\
suggested file 'output-name' and access mode.  If the 'output-name' is\n\
specifically '/dev/stdout', then 'uudecode' will emit the decoded file to\n\
standard out.\n\n\
'Note': 'uuencode' uses buffered input and assumes that it is not hand\n\
typed from a tty.  The consequence is that at a tty, you may need to hit\n\
Ctl-D several times to terminate input"));
  /* copyright.type */
  puts(_("This program is released under the terms of the GNU General Public License, version 3 or later."));
}
#endif /* uncompilable code */
#ifdef  __cplusplus
}
#endif
/* uuencode-opts.c ends here */
